### ISSUE TITLE
ruutu.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#10]
Watching videos on ruutu.fi with adblocker turned on will result a complaint to disable adblocker. Videos also won't play then.

a sample:
`https://www.ruutu.fi/video/3255174`

The problem can be fixed with these filters:

This filter makes videos to work:
`@@||fwmrm.net/ad/$script,domain=ruutu.fi`

And this filter blocks the remaing ads that are shown after using the fix filter above:
`||nelonenmedia.fi/ads/$media,domain=ruutu.fi`

Here is also a filter to block Ruutu from advertising Ruutu+ on the bottom (a banner ad):
`ruutu.fi##.t5tj6d-0.vdqQx`

**Comment by theel0ja** [comment]
Fixed in #5.
