### ISSUE TITLE
happypancake.fi - Anti-adblocking in the chat

### ISSUE THREAD

**Issue by krisu5** [finnish-easylist-addition/finnish-easylist-addition#103]
### List the website(s) you're having issues:

`https://www.happypancake.fi/messages`

### What happens?

After loading the URL, wait for 10-20sec to that anti-adblock message appear. It disables chat's message box at the bottom.

You don't need to start a chat with a person, just loading that page is enough.

### List Subscriptions you're using:

- uBlock filters – Annoyances​​​​​
- uBlock filters – Badware risks​
- uBlock filters – Experimental​
- uBlock filters – Privacy​​​​​
- uBlock filters – Resource abuse​​​​​
- uBlock filters – Unbreak​​​​
- Adblock Warning Removal List​
- AdGuard Base filter​
- EasyList​
- AdGuard Spyware filter​
- EasyPrivacy​
- Malvertising filter list by Disconnect​​​​​
- Malware Domain List​​​​​
- Malware domains​
- Spam404
- AdGuard Annoyances filter​
- Anti-Facebook List​
- Fanboy's Cookie List​
- FIN: Adblock List for Finland

- https://ssl.bblck.me/blacklists/ublock-origin.txt
- https://raw.githubusercontent.com/bcye/Hello-Goodbye/master/filterlist.txt
- https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
- https://raw.githubusercontent.com/IDKwhattoputhere/uBlock-Filters-Plus/master/uBlock-Filters-Plus.txt

### Your settings

- OS/version: Windows 10 Home, build 1809
- Browser/version: Firefox 66.0.2
- Adblock Extension/version: uBlock Origin 1.18.16

### Other details:
[I also reported it in NanoFilters repo](https://github.com/NanoAdblocker/NanoFilters/issues/303) (bit more info there, screenshots etc.)

**Comment by krystian3w** [comment]
@kiboke you accept cookies after logon:

```
https://www.happypancake.fi/noconsent?redirect=/discover
```

?

**Comment by krystian3w** [comment]
for chat now works exceptions, I suppose possible fix with scriplets:

```
@@||happypancake.fi/static/show_ads.js$script,domain=www.happypancake.fi
@@||happypancake.fi/static/prebid.*.js$script,domain=www.happypancake.fi
@@||googletagmanager.com/gtm.js$script,domain=www.happypancake.fi
```

**Comment by krisu5** [comment]
> 
> 
> @kiboke you accept cookies after logon:
> 
> ```
> https://www.happypancake.fi/noconsent?redirect=/discover
> ```
> 
> ?

Yes, because

**Comment by krisu5** [comment]
> @kiboke you accept cookies after logon:
> 
> ```
> https://www.happypancake.fi/noconsent?redirect=/discover
> ```
> 
> ?

Yes, because unfortunately you can't use service at all if you don't consent (you probably noticed already).


> for chat now works exceptions, I suppose possible fix with scriplets:
> 
> ```
> @@||happypancake.fi/static/show_ads.js$script,domain=www.happypancake.fi
> @@||happypancake.fi/static/prebid.*.js$script,domain=www.happypancake.fi
> @@||googletagmanager.com/gtm.js$script,domain=www.happypancake.fi
> ```
> 
> `happypancake.fi##+js(set, canRunAds, true)` if we don't load `show_ads` in the feature.

Unfortunately, this didn't work for me at least :/

**Comment by krystian3w** [comment]
Try change:

`security.csp.enable` false from

 `about:config`.

Also disable Firefox Tracking protection or remove tracker by disconnect in this mechanizm.

**Comment by krisu5** [comment]
> Try change:
> 
> `security.csp.enable` false
> 
> from `about:config`.

Confirming that this works, also uBlock has to be on easy mode.

**Comment by peace2000** [comment]
How is this today? I made a test account and I don't see an antiadblock message here: https://www.happypancake.fi/messages

**Comment by krisu5** [comment]
Yeah, there's no anti-adblock message anymore. It was removed?

(Disabled krystian3w's rules, re-enabled CSP, medium mode seems to work too.)

**Comment by krystian3w** [comment]
#### off topic:

Firefox 69+ may no need  disable CSP.

**Comment by peace2000** [comment]
> 
> 
> Yeah, there's no anti-adblock message anymore. It was removed?
> 
> (Disabled krystian3w's rules, re-enabled CSP, UBO's medium mode seems to work too.)

Ok, I'll close this issue then if it's ok. This has been open pretty long time... :D

**Comment by mapx-** [comment]
https://github.com/NanoAdblocker/NanoFilters/issues/564

do you have an account ?

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/65125
