### ISSUE TITLE
mtv.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#12]
This site uses ads for videos. Video based ads and ad images every time the video is paused.

A sample video:
`https://www.mtv.fi/sarja/peter-nyman-33001036002/rasanen-haluaa-ymmartaa-aborttiin-paatyneita-mutta-muistuttaa-suomessa-ei-synny-ei-toivottuja-lapsia-1009128`

To block video ads:
`||damoh.katsomo.fi/*$media,redirect=noopmp3-0.1s,domain=mtv.fi`

To block ad images that appear during a pause:
`||damoh.katsomo.fi/*$image,redirect=noopmp3-0.1s,domain=mtv.fi`

However even though ad images are blocked the whole video area remains clickable (clicking opens a popup to another site). Also continuing the video playback is prevented. These problems can be fixed with this filter:
`mtv.fi##.mtv-player-ad-container`

Note: this filter compilation works for Ublock Origin only. I could not make filters for Adblock Plus.

**Comment by peace2000** [comment]
This filter can also be removed as everything works fine without it:

```
! mtv videoihin toimintavarmuutta
@@||st.mtv.fi/static/javascripts/external-js/detectmobilebrowser.js?
```

**Comment by theel0ja** [comment]
However, we could to make list for uBO-specific stuff? Don't know if it is an good idea though.

**Comment by theel0ja** [comment]
Or maybe just contribute them to uBlock Origin integrated filterlists.

**Comment by ZaphodBeebblebrox** [comment]
If you want, you can use [pre-parsing directives](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#pre-parsing-directives) to load more filters only in uBO/Adgaurd, since they are the only adblockers that support them. This would allow you to have more filters for adblockers that support them without putting a bunch of rules that do not work in the list for ABP

**Comment by peace2000** [comment]
Partly good news!

I was pointed out `https://forums.lanik.us/viewtopic.php?p=143224#p143224` that image redirect rule is bad. Instead this should be used:

`||damoh.katsomo.fi/*$image,domain=mtv.fi`

The good thing is that this rule is compatible with ABP also!

**Comment by peace2000** [comment]
#20
