### ISSUE TITLE
Status of list preinstalled into popular Adblockers

### ISSUE THREAD

**Issue by theel0ja** [finnish-easylist-addition/finnish-easylist-addition#13]
## List of progress

- [x] 1Blocker (email contact 12.02.2020, under consideration, plans to add language lists more in the future)
- [x] AdBlock Plus
- [x] AdGuard
- [x] Adblocker Ultimate (email contact)
- [x] Brave (https://github.com/brave/ad-block/issues/144)
- [x] FilterLists.com (https://github.com/collinbarrett/FilterLists/pull/628)
- [x] getAdblock.com
- [x] uBlock Origin (https://github.com/gorhill/uBlock/pull/3743)

**Comment by ZaphodBeebblebrox** [comment]
In uBO's next release. gorhill/uBlock@8d6bb24

**Comment by DandelionSprout** [comment]
If you guys (or anyone else) do find a way to get it natively included in ABP, then feel free to tell me how that was accomplished. Because I've been mystified when it comes to figuring out how to do that, and have so far settled for merely being included in https://adblockplus.org/subscriptions, which hardly anyone really checks out.

**Comment by peace2000** [comment]
Should also get this list here:

https://filterlists.com/

**Comment by peace2000** [comment]
It's on https://filterlists.com/ thank you DandelionSprout for your pull request I noticed. :)

**Comment by DandelionSprout** [comment]
Regarding native inclusion in Adblock Plus in general, I've received this feedback for a thread that I had posted to the EasyList forums (Slightly abbreviated): 

>Hi [Dandelion Sprout],
>
>intense from the EasyList forum pinged me about [including your filter list in ABP](https://forums.lanik.us/viewtopic.php?f=23&t=42273).
>
>At ABP we have some requirements for new filter lists. You can look them up here: https://adblockplus.org/filter-lists-requirements
>
>Usually before offering a filter list together with EasyList we would ask the other EasyList authors for feedback about the list.
>
>Let me know if you have any questions!
>
>I might not be able to respond in a timely manner this week
>
>Best regards,
>Arthur [Kawa]
>Filter Developer & Filter List Author Manager

So from what I can determine, both the guidelines of https://adblockplus.org/filter-lists-requirements and of https://easylist.to/pages/policy.html would have to be taken into consideration, if a list wants to be included in ABP.

**Comment by peace2000** [comment]
Added more lists to the first message.

**Comment by DandelionSprout** [comment]
I was about to suggest that maybe pfBlockerNG could be added to the OP, until I doublechecked [their list info file](https://github.com/pfsense/FreeBSD-ports/blob/devel/net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json) and saw it was already there. 🎉

They use a pretty boring template for when they add major adblocker-syntax lists, so it's a possibility to change the list info if you were to want to do so.

**Comment by peace2000** [comment]
In Adblock Plus, Finnish Easylist is loaded as a part of Nordic filterlist.

**Comment by peace2000** [comment]
https://getadblock.com can be checked as well, it seems that they use @DandelionSprout nordic filters as well, meaning that the Finnish list is used as a part of it as well.

A long time ago I asked about this in their forums, they answered once but never came back to me concerning this matter... Now their forums seem to be deprecated though they have some kind of ticketing system now...

Frankly, this process has been pretty appalling. I can't understand this lack of interest some Adblocker developers have shown in adding a county specific list, which should be a high priority interest for any adblocker tool. Though some Adblocker developers reacted very quickly, gotta give them that.

**Comment by DandelionSprout** [comment]
It seems that AdBlock have indeed switched to the ABP-intended version of Nordic Filters, instead of [the non-Finnish, pro-AAB AdBlock-intended version they used for a couple years](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP.txt).
