### ISSUE TITLE
123pelit.com

### ISSUE THREAD

**Issue by krystian3w** [finnish-easylist-addition/finnish-easylist-addition#130]
cookie:

![obraz](https://user-images.githubusercontent.com/35370833/64457053-f0f82200-d0f1-11e9-892d-9b70d9ccde82.png) |
--- |

`###app-root > .K`

or if `K` is not stable:

`###app-root > footer ~ aside:first-of-type:last-of-type`

---

cookie leftover after second visit:

![obraz](https://user-images.githubusercontent.com/35370833/64457074-fc4b4d80-d0f1-11e9-8696-fa982df3a153.png) |
--- |

`##button[class][title="Show CMP"]`

**Comment by peace2000** [comment]
Hi! I appreciate your efforts but as this is a cookie notice, I think it would better fit to Fanboy's cookie list: https://github.com/ryanbr/fanboy-adblock/issues

**Comment by peace2000** [comment]
I reported it: https://github.com/ryanbr/fanboy-adblock/issues/1166
