### ISSUE TITLE
mtvuutiset.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#14]
This site shows ads during video playback (video ads and image ads during a paused video) so here are (Ublock only) compatible filters for this site to remove ads:

To block video ads:
`||damoh.katsomo.fi/*$media,redirect=noopmp3-0.1s,domain=mtvuutiset.fi`

To block ad images during paused content:
`||damoh.katsomo.fi/*$image,redirect=noopmp3-0.1s,domain=mtvuutiset.fi`
`||cloudfront.net/creatives/assets/$image,redirect=noopmp3-0.1s,domain=mtvuutiset.fi`

To remove the remnant clickable popup opener area in videos, left by blocked ad images and to make paused video playback work again:
`mtvuutiset.fi##.mtv-player-ad-container`

Sample videos:
`https://www.mtvuutiset.fi/artikkeli/norjan-puolustusministerio-vahvistaa-venaja-hairitsi-gps-signaalia-naton-harjoituksen-aikana-lapissa/7163010`
`https://www.mtvuutiset.fi/artikkeli/michelle-obama-puhuu-avoimesti-26-vuotisesta-avioliitostaan-kertoo-hakeutuneensa-vaikeina-aikoina-parisuhdeterapiaan-se-oli-tukipisteeni/7161286`

**Comment by theel0ja** [comment]
Some of these can be found from uBlock filters.

**Comment by peace2000** [comment]
Partly good news!

I was pointed out `https://forums.lanik.us/viewtopic.php?p=143224#p143224` those image redirect rules are bad. Instead these should be used:

`||damoh.katsomo.fi/*$image,domain=mtvuutiset.fi`
`||cloudfront.net/creatives/assets/$image,domain=mtvuutiset.fi`

The good thing is that this rule is compatible with ABP also!

Also this is needed and it's compatible with Ubo and ABP:

`mtvuutiset.fi##.mtv-player-ad-container`

**Comment by theel0ja** [comment]
These can be found from uBO filters.

https://github.com/uBlockOrigin/uAssets/blob/2e293dcb6e22fefcc5f994191cd3da44dd0e6135/filters/filters.txt#L13582-L13583

https://github.com/uBlockOrigin/uAssets/blob/2e293dcb6e22fefcc5f994191cd3da44dd0e6135/filters/filters.txt#L13607-L13611

**Comment by theel0ja** [comment]
https://github.com/uBlockOrigin/uAssets/blob/1e492a59913982e29a4a5bcff5ec4f9f24bddfce/filters/filters.txt#L13370-L13373

https://github.com/uBlockOrigin/uAssets/blob/1e492a59913982e29a4a5bcff5ec4f9f24bddfce/filters/filters.txt#L13582-L13583

https://github.com/uBlockOrigin/uAssets/blob/1e492a59913982e29a4a5bcff5ec4f9f24bddfce/filters/filters.txt#L13607-L13611
