### ISSUE TITLE
hs.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#15]
Hi, I noticed an ad when test watching this video:
`https://www.hs.fi/kaupunki/art-2000005898822.html`

The same ad server can also be encountered here:
`https://www.is.fi/ulkomaat/art-2000005898948.html`

Since Nelonen Media `https://en.wikipedia.org/wiki/Nelonen_Media` is a corporation that owns many sites it's better to make a general filter rule for it's ad server:

`||ads-manual02.nelonenmedia.fi^$media`

**Comment by theel0ja** [comment]
Already here.

https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/6a311a0e38831d7e06f9f51f84a29a639aaf2201/Finland_adb.txt#L833-L834

**Comment by peace2000** [comment]
Update.

Nelonen Media has these two ad servers they use on their sites:

`ads-manual02.nelonenmedia.fi`

`ads-spotgate02.nelonenmedia.fi`

Both of them can be blocked everywhere with this general filter:

`||nelonenmedia.fi/ads/$media`

Sorry for hassling around with these but you always learn new things. :D

**Comment by peace2000** [comment]
#18

**Comment by peace2000** [comment]
#18

**Comment by peace2000** [comment]
#19 I hope I made a pull request correctly this time.

**Comment by theel0ja** [comment]
I'd suggest, that you type like "Fixes #19" into your pull requests so it automatically closes the issues when PR is approved.

**Comment by peace2000** [comment]
All right I'll do that next time.
