### ISSUE TITLE
Old filters

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#17]
Old address
`kansi.a-lehdet.fi/spring.js`

Potential useless rule:
`adslm.a-lehdet.fi/www/delivery/ `

This has quit `https://fi.wikipedia.org/wiki/Keltainen_P%C3%B6rssi`:
```
keltainenporssi.fi##div[id="dBannerTop"]
keltainenporssi.fi##table[id="master_container"]>tbody>tr>td>table>tbody>tr:first-child
```

Changed domain to `kelkkasivut.kelkkalehti.com`
`kelkkalehti.com/bannerit/`

Dont' see a point for this rule not an adblock rule:
`nayadaya.com$third-party`

Useless filter and a foreign site (edit by @theel0ja: tracker I think):
`pingdom.net/`

Page not found
`nuuh.alma.iltalehti.fi`

Not an adblocking rule and domain changed to `www.hs.fi/nyt`
`nyt.fi##DIV#javascript-disabled-error`

Non-working domain
`ratas.sanoma.fi/`

Domaint changed to `keskustelu.sammysatv.com`
```
sammysatv.com##center
sammysatv.com##a[href*="banner"]
```

"misconfigured domain"
`static.sanoma.fi/weba/js/ls/zig.js`

Non-working domain
`dco-de.sanoma.fi/ussr-ts/sputnik`

Non-working probably useless:
```
sat.sanoma.fi/js
sat.sanoma.fi/sat
```

Not sure probably useless
`sfnix.net/api/`

Useless rule and a foreign site:
```
spy-sts.com
```

Probably expired:
`stream.almamedia.fi/mp/salsabanner`

Dead domain
`suomensanomat.fi##div[class="static-info"]`

Foreign site and domain change anyway
`timeinc.com/trending`

Changed domains and not adblocking rules
```
tinypass.com/*/track
tinypass.com/*/meter/
```

Not adblocking rule and not sure if relevant anymore anyway
`tivi.fi/Logger`

Domaing change to monster.fi (filter might also be old)
`uratie.fi/external/json/?service=jsonSidebar&`

Expired domain
`uutismaailma.com##DIV[class="top_banner"]`

Probably expired rule
`vaalikone.fi/*/preheat`

Not relevant
`vilagnomad.com`

Domain does not work
`wallpapers.red`

Don't see the point for this:
`pls.webtype.com/v.gif`

These are not ads:
```
yle.fi/.*yle-analytics
metrics.api.yle.fi
analytics-sdk.yle.fi
```

Some tracking I guess
`xiti.com`

Cannot access domain and could be old also (note by @theel0ja, it's `wpengine.com` wordpress hosting, actually up, for example `s3-torquehhvm-wpengine.netdna-ssl.com`)
`wpengine.netdna-ssl.com/*/moottori/*/popup*.js`

Non-finnish
`horizonsunlimited.com##a[href*="9mmff.com"]`

Non-needed whitelisting
```
! mtv videoihin toimintavarmuutta
@@||st.mtv.fi/static/javascripts/external-js/detectmobilebrowser.js?
```

So much old stuff...

There are probably more tracking related stuff that does not IMO belong to adblocker list. There are other lists for that such as EasyPrivacy.

**Comment by theel0ja** [comment]
Btw, you could also create a pull request for quicker modifications.

Just click Edit (pen) button on the file you want to send modification to.

For example: https://github.com/finnish-easylist-addition/finnish-easylist-addition/edit/master/Finland_adb.txt

**Comment by peace2000** [comment]
Ok I'll try to learn how to use this site. :D

**Comment by theel0ja** [comment]
@peace2000 make a pull request to suggest edits to this repo's master branch

**Comment by theel0ja** [comment]
See https://github.com/finnish-easylist-addition/finnish-easylist-addition/issues/15#issuecomment-438767130

**Comment by jounihh** [comment]
Why can't merge any of the pull requests that remove a lot of filters. I think the reason why this list isn't in adblock plus is because there are so many old filters and duplicates and tracking and stuff that shouldn't be in this list.
