### ISSUE TITLE
www.iltalehti.fi - Front page won't load content

### ISSUE THREAD

**Issue by The-Paavo** [finnish-easylist-addition/finnish-easylist-addition#247]
### List the website(s) you're having issues:

`https://www.iltalehti.fi/`

### What happens?

Front page won't load content/articles. It loads only third party content (kauppalehti.fi, autotalli.com).

### List Subscriptions you're using:

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
Adblock Warning Removal
AdGuard Base
AdGuard Mobile Ads
EasyList
AdGuard Tracking Protection
EasyPrivacy
AdGuard Annoyances
Fanboy’s Annoyance
uBlock filters – Annoyances
FIN: Adblock List for Finland
Annoyance List for Finland
Block-EU-Cookie-Shit-List

### Your settings

- Windows 10
- Edge 79.0.309.68
- uBlock Origin 1.24.2

### Other details:

This is caused by commit: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/669028398a4f251aa51588634da042ee7ee53228

If I revert that with my own exception rule `iltalehti.fi#@#div.fp-container.card` - front page loads content (articles) as it should.  NOTE: this affects only front page of Iltalehti.fi AFAIK.

**Comment by peace2000** [comment]
Yes this rule is now problematic because Iltalehti changed element names, this rule was originally used solely for commercial articles but they made changes and now this rule is also used for frontpage articles. I made a fix for this yesterday, have to wait for @theel0ja to accept it. :)

**Comment by The-Paavo** [comment]
Sweet. Now we just wait patiently. Thank you!

**Comment by SuperHirmu** [comment]
It's been broken for several days already. Chop chop! This is taking too, too, too damn long. Any given project may have outlived its usefulness by the time implementing minor, trivial changes becomes seemingly impossible undertaking involving huge pain and labor. Maybe just disable "Adblock list for Finland" and try to survive without.

**Comment by peace2000** [comment]
@SuperHirmu nyt meni vähän ohitse tuo "Any given project" -alkuinen lause.

Joo tosiaan kunnes fixi hyväksytään, niin jokainen pystyy itseltään korjaamaan asian näillä whitelist-säännöillä:

`iltalehti.fi#@#div.fp-container.card`

`iltalehti.fi#@#.title:xpath(//div[contains(text(), 'Kaupallinen yhteistyö')]):xpath(../../..)`

Ensimmäinen korjaa etusivun, jälkimmäinen joitain alasivuja.

**Comment by SuperHirmu** [comment]
Joo moi, mielenkiintoa on näköjään ihan hurjana --

! Version: 201907071
! Title: Adblock List for Finland
! Description: Finnish adblock list
! Last modified: 20th of June 2019

Kai tajuat että tämä Suomi-suodatuslista jaellaan oletusarvoisesti esim. suomenkielisen Chromen käyttäjälle joka haluaa asentaa µBlock Originin? Eli kaikilla näillä juusereilla on iltalehti.fi ja ties mitä muuta rikki, ja täällä mietitään "fixin hyväksyntää" ties kuinka monetta päivää. Voi hyvänen aika sentään. Voin ilmoittaa ettei kukaan varmasti ala käsipelillä whitelistaamaan mitään sellaista minkä PITÄÄ toimia out of the box. Haloo! Jos ei kiinnosta tämän enempää, kannattaa ilmoittaa että projekti on kuollut, ja etsitään uutta ylläpitoa.

**Comment by peace2000** [comment]
Joo on tää ikävä tilanne mutta asia ei nyt oo mun käsissä. Noilla whitelisteillä voi itselleen asian korjata tai olla korjaamatta.

**Comment by peace2000** [comment]
Let's see if Ubo's upkeepers could made a fix through Ubo's internal filters:

**Comment by mapx-** [comment]
- fixed for uBo
https://github.com/uBlockOrigin/uAssets/commit/d109681b5e32d0297359de4ce4920e8fbb426f2a
- @peace2000 in the future report directly at uAssets repository

**Comment by peace2000** [comment]
Thanks! Yeah, will do.

**Comment by theel0ja** [comment]
@SuperHirmu 

> ! Last modified: 20th of June 2019

The last modified date hasn't been updated in long time, but there has been pull requests.

**Comment by peace2000** [comment]
This issue can be closed now, as the problematic rules have been removed.

I also have been given now a write access to this list so there are more people to maintain this list as editors. :)
