### ISSUE TITLE
is.fi gets blocked due to typo

### ISSUE THREAD

**Issue by nilikka** [finnish-easylist-addition/finnish-easylist-addition#250]
### List the website(s) you're having issues:

https://is.fi

### What happens?

Whole site gets bloked thanks to typo in commit baceb1196f7cf8625abb490bda9c5aff6562d6f7 on 3.5.

### List Subscriptions you're using:

Not applicable, rule comes from this list

### Your settings

- OS/version: Not applicable
- Browser/version: Not applicable
- Adblock Extension/version: Adguard Home

### Other details:

Commit baceb1196f7cf8625abb490bda9c5aff6562d6f7 made on 3.5. has a typo in it

Finland_adb.txt row 443

**Comment by peace2000** [comment]
Fixed. GH will process the fix in 5-10 minutes.
