### ISSUE TITLE
I'm planning to nominate your list to ABP, and need your thoughts on it

### ISSUE THREAD

**Issue by DandelionSprout** [finnish-easylist-addition/finnish-easylist-addition#251]
Okay, so here's the situation: I'm seemingly just days away from holding an official paid position at Eyeo, with responsibility for the entire Nordics, and with the benefit of finally getting a specific version of my Nordic list included in ABP.

However, my list will (as it currently stands) only cover Norway, Denmark and Iceland. And Sweden will become a pretty big headache, since it seems that I and/or Eyeo will have to hardfork @lassekongo83's list to manually remove anti-anti-adblock entries (which Eyeo are not fond of), presuming such a fork would even be permitted by Frellwit and his GPL3 licence. So I'm hoping to try to sort out a fast-lane agreement for you for Finland so that I have one less headache to take care of:

Given the following options, would you want to:
1) agree to my nomination of *Adblock List for Finland* in ABP, and have me serve as the guy who'd read through Finland-specific ABP issue form reports, with Eyeo-side fixes added directly to your list? If yes, would I be given push rights to the list once it's included, or do you want me to just use PRs?
2) agree to my nomination of *Adblock List for Finland* in ABP, and have me serve as the guy who'd read through Finland-specific ABP issue form reports, with Eyeo-side fixes instead added to a separate file at https://hg.adblockplus.org/customfilterlists/file/default, which are then merged with an ABP-hosted mirror of your list?
3) request to Eyeo that you yourself would want a job at their place to assist in taking care of Finland and Sweden, and hope that they have room for one more guy from the Nordics?
4) reject having your list be included in ABP at all, at which point a brand new Finland-specific list would most likely need to be created and maintained by me specifically for ABP?
5) something else?

**Comment by DandelionSprout** [comment]
If you're unsure, or want to ask a couple ABP people about the matter, they're (most likely) available for questions in a Slack group for filterlist makers for which you are cordially invited, but which you'll (as I've understood it) have to ask Fanboy to get an invite link for. I've also linked to this thread in that Slack group.

**Comment by peace2000** [comment]
Thanks for this! We'll soon come back to this. :)

**Comment by peace2000** [comment]
I have sent mail to @theel0ja who is the repo owner, but unfortunately he has been busy so I haven't got his response. But I'm sure that the option number 1 is good way to go. Currently you can only send PR's, unless thee0ja grants you writing access to this repo.

Problems with the option number 2 would be that it would be hard to manage things if they'd be needed to manage on 2 different locations.

What it comes to option number 3, I'm fine with the status quo. :)

It would be great to have this list included in the ABP.

**Comment by peace2000** [comment]
@DandelionSprout (Just tagging to be sure :) )

**Comment by DandelionSprout** [comment]
I did see it at the time it was written, admittedly. 😄 

My first work week was spent mostly on making own list meet additional legal requirements (of which there's a lot; including one saying that I couldn't use the word 'Eyeo' inside a list that was ran from my own repo) and being gradually introduced into the work environment.

That being said, I feel optimistic that option 1 would be put into motion inside of 3 weeks from now, though it's a loose assumption.

**Comment by peace2000** [comment]
Ok. :) Thanks for letting me know!

**Comment by peace2000** [comment]
@DandelionSprout Hi, Is it good time now to start the process?

**Comment by DandelionSprout** [comment]
It's going far more slowly than I was hoping for. I've added it to their official to-do list at https://gitlab.com/eyeo/adblockplus/adblockpluscore/-/issues/243, but it appears their main priority is to have my list be added to ABP 3.10.0 in ~2 weeks first.

**Comment by peace2000** [comment]
Oh. Well, hopefully in the near future at least then. But how come that request has blocked label?

**Comment by DandelionSprout** [comment]
From what I can tell, it's fancy coders' way of saying that the issue report is unable to be dealt with, until they first solve whatever other problems they'd have.

In this specific case, it seems they're taking their sweet time to go through and review the Finnish list.

**Comment by peace2000** [comment]
Okey, if they have questions about any entries in the list, just ask. :)

**Comment by peace2000** [comment]
@DandelionSprout Hi, do you have idea how is this doing?

**Comment by DandelionSprout** [comment]
By now I genuinely have no idea what is going in the ABP GitLab repo. The codebase team's apparent leader, Hubert Figuière, has been consistently ignoring virtually all wishes and requests from filterlist maintainers (e.g. me, Fanboy, Dimisa), and even wishes from ABP's filterlist team (e.g. Joana Garcia). It is unclear if Hubert is either focusing entirely on Manifest V3 or if he actually doesn't understand what people are asking him to implement.

**Comment by peace2000** [comment]
All right, thanks for a update. That's bad.

**Comment by DandelionSprout** [comment]
From Joana Garcia on Slack yesterday:

*"(…) I can tell you that at the moment we are not planning to add more recommend filter lists due to [Manifest] v3. As you know we will have to deal with a limit of filters and having another list (with more filters) it isn't something wise to do now. Also when we think of adding new recommended lists we need to think of browser languages that have not been covered by abp recommended lists. At the top there is turkish. One think that I remember we talked about was the nordic list covering finish websites. I sent an email that I will be on holidays until 4th of January so we can discuss this further in January. If you or anyone has other topics that eyeo should follow up on just write them down so we can take from there in January.
This year has been really weird but I am sure 2021 can't be worse"*

Seemingly the decision was made last week, and they never thought about announcing this decision to filterlist makers (before yesterday) or to the GitLab team. So in an attempt to avoid excessive and confusing bureaucracy between the different Adblock Plus workteams, I've now taken matters more or less into my own hands and took her on her words about *"the nordic list covering finish websites"*, at least for the next few months: https://github.com/DandelionSprout/adfilt/commit/ddbea426935951566835b663c1ec4fade9cf3878

**Comment by peace2000** [comment]
All I've heard about that manifest v3 thing is bad. What I understand it's only going to concern Chrome in the near future? Are there any ways to bypass those limitations or work around them in the future? I'm not a programmer so I don't know about this stuff too much.

But yeah, that idea of having one Nordic list is probably the best way to go now. Though that list does not activate automatically for Finnish ABP users and it's name / description in ABP does not indicate at first glance it has a Finnish list included. Would changing these things require a new updated version of ABP?

**Comment by DandelionSprout** [comment]
Regarding your questions on Manifest V3; back when it was originally announced a year and a half ago, it was very limited (Max 50,000 rules; lacked `:-abp-has` and `:-abp-contains`), comparable to what Safari has been like in the past few years. There are indications that it's become less crap between then and when the official implementation was implemented in Chrome Canary some weeks ago (300,000 rules, keeps almost all hiding syntaxes), but I still don't trust it.

It is believed to only become mandatory in Chrome from January 2022 onwards, with Vivaldi and Brave saying they'd consider it extremely important to retain V2 in their codebases when Chrome removes it from Chromium.

>Would changing these things require a new updated version of ABP?

Most likely. That alone could take another 3 months if we've got bad luck.

**Comment by peace2000** [comment]
Thanks for a reply. Let's see what happens in January then.

**Comment by hfiguiere** [comment]
> By now I genuinely have no idea what is going in the ABP GitLab repo. The codebase team's apparent leader, Hubert Figuière, has been consistently ignoring virtually all wishes and requests from filterlist maintainers (e.g. me, Fanboy, Dimisa), and even wishes from ABP's filterlist team (e.g. Joana Garcia). It is unclear if Hubert is either focusing entirely on Manifest V3 or if he actually doesn't understand what people are asking him to implement.

I will reiterate what I said previously: `adblockpluscore` doesn't make decisions on which list are included. It is the responsibility of the FDA team, and this is done by adding an entry to the subscriptionlist repository and requesting us to update. If it is not there, nothing can be done, hence the "blocked" label. *no exceptions* 

Your original issue put the cart before the horse.

**Comment by mile-ne** [comment]
Hey!
I would suggest to close this issue as it is creating too much noise and not adding much value.

Maybe for the future, the best would be that you, @peace2000 as finnish maintainer would send an email directly to eyeo as a github issue doesn't seem the best way to go over this.
As @hfiguiere mentioned there is a team who can explain more about requirements for an inclusion of a list to abp and after proceed with the review according to a policy. Hubert's team only takes care of including the already approved list in the release.

I would be happy to talk about a Finnish list but in no way promising that there will be an immediate inclusion. Here is the contact: fda@eyeo.com

**Comment by DandelionSprout** [comment]
Some things I want to apologise for, presuming this is the correct place to do so at:

1) I officially apologise to @hfiguiere, and withdraw the accusations he quoted above, since they were written before https://gitlab.com/eyeo/adblockplus/adblockpluscore/-/issues/243#note_477520280 established that he was innocent in this situation.
2) I wrote the OP back in June, before I knew that lists could only be added in major iterations (3.8.0, 3.9.0, 3.10.0, etc.), before I knew it could go 5 months between major iterations, and while being under the belief that there were supposed to be lists covering the entire Nordics very soon after I got a job position for the Nordics.
3) In the days following the accusations, I began realising that I should've set up some way to establish a convo group for all 4 of us (Me, Joana, Hubert, and peace2000), so that I wouldn't need to keep 3 different communications about it with people who had drastically different knowledge of what was happening in general. By the time I realised that, it was too late to do such.

I'll close this issue report once we get confirmation from peace2000 (or alternately theel0ja, who seems to have ceased working on this list) that he has read Joana's message above.

**Comment by peace2000** [comment]
Thanks for these updates, I'll send an email to that address and close this issue then. Let's continue through email. :)

**Comment by peace2000** [comment]
I tried to sent mail but it failed:

![kuva](https://user-images.githubusercontent.com/17256841/104105448-c8200800-52b6-11eb-96cc-96aecc2c6a56.png)

@mile-ne ?

**Comment by peace2000** [comment]
Any other ways to contact?

@DandelionSprout @hfiguiere ?

**Comment by mile-ne** [comment]
> Hey!
> I would suggest to close this issue as it is creating too much noise and not adding much value.
> 
> Maybe for the future, the best would be that you, @peace2000 as finnish maintainer would send an email directly to eyeo as a github issue doesn't seem the best way to go over this.
> As @hfiguiere mentioned there is a team who can explain more about requirements for an inclusion of a list to abp and after proceed with the review according to a policy. Hubert's team only takes care of including the already approved list in the release.
> 
> I would be happy to talk about a Finnish list but in no way promising that there will be an immediate inclusion. Here is the contact: [wizards@adblockplus.org](mailto:wizards@adblockplus.org)
> @peace2000 just edited the email since the one before doesn't get mails from externals and I also couldn't find you on slack

here @peace2000

**Comment by peace2000** [comment]
@mile-ne Thanks, mail sent.
