### ISSUE TITLE
Prisguiden.no - Blocked buttons / price info (Adblock List for Finland)

### ISSUE THREAD

**Issue by THEtomaso** [finnish-easylist-addition/finnish-easylist-addition#252]
### Affected site:
`https://prisguiden.no/`

### Issue:
Blocked buttons / price information.

### Example:
`https://prisguiden.no/produkt/makita-dur181z-uten-batteri-297783/`

### Screenshot:
![filterissue-prisguiden](https://user-images.githubusercontent.com/9382674/84052929-82623080-a9b1-11ea-8d13-8efac576447d.jpg)

### Problem filter:
* Adblock List for Finland

### Problem rule:
`##a[href*="adtraction.com"]`

### Possible fix:
```
- ##a[href*="adtraction.com"]

+ ##a[href*="adtraction.com"]:not(.button-to-shop):not(.link-to-shop)
+ ||track.adtraction.com^
```

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.10.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by peace2000** [comment]
I decided to remove that rule completely. I tested some sites that use that domain https://publicwww.com/websites/%22adtraction.com%22/ and it seems that a network filter is enough. The main Easylist already has a network filter:

`||adtraction.com^$third-party`
