### ISSUE TITLE
iltalehti.fi one specific article false-positive (fixed now)

### ISSUE THREAD

**Issue by tl0** [finnish-easylist-addition/finnish-easylist-addition#257]
### List the website(s) you're having issues:

`https://www.iltalehti.fi/politiikka/a/90650421-76d3-4ea5-be86-8593c8ed1b70`

### What happens?

The article is not an ad, but gets incorrectly matched, because it contains wording "kaupallinen yhteistyö".

![image of section](https://i.imgur.com/lA6s2xX.png)

### Other details:

Pretty sure [this](https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/2f717582fbf947a3c7ecd489ca960c30cda37cd8/Finland_adb.txt#L248) is the rule affecting.

I don't know if anything should be done about this, as it is very rarely happening false-positive and can be easily bypassed by "experienced" users using cosmetic filter toggle -button
![cosmetic filter button](https://i.imgur.com/IBYDbMP.png)

**Comment by peace2000** [comment]
This can probably be closed now.
