### ISSUE TITLE
io-tech.fi & bbs.io-tech.fi

### ISSUE THREAD

**Issue by veikk0** [finnish-easylist-addition/finnish-easylist-addition#259]
### List the website(s) you're having issues:

`https://www.io-tech.fi/`
`https://bbs.io-tech.fi/`

### What happens?

There's a banner ad at the top of the page on both these sites.

### List Subscriptions you're using:

All built-in uBlock filters, EasyList, EasyPrivacy, [Malicious Online URL Blocklist](https://gitlab.com/curben/urlhaus-filter#urlhaus-malicious-url-blocklist), uBlock filters - Annoyances, Peter Lowe’s Ad and tracking server list, this filter list

### Your settings

Disabled all the extensions listed in the issue template.

- OS/version: Linux Mint 19 Tara 64-bit
- Browser/version: Firefox 81.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.30.2

### Other details:

![io-tech](https://user-images.githubusercontent.com/7808922/95669771-cd24cc80-0b8c-11eb-8ce4-571f04326c8f.png)
![io-tech-bbs](https://user-images.githubusercontent.com/7808922/95669773-d44bda80-0b8c-11eb-9fe8-af4fd0185acb.png)

**Comment by peace2000** [comment]
Refresh your lists after 10 minutes.
