### ISSUE TITLE
tori.fi frontpage - new car listings

### ISSUE THREAD

**Issue by 07416** [finnish-easylist-addition/finnish-easylist-addition#261]
### List the website(s) you're having issues:

`https://www.tori.fi/`

### What happens?
Apparently promoted used car offers are shown:
![Screenshot_2020-10-11 Tori fi - Osta ja myy helposti Ilmoita ilmaiseksi Torissa ](https://user-images.githubusercontent.com/14923168/95673604-cad56900-0bb2-11eb-860d-50d9658e9565.png)

### Other details:

suggested filter:
`tori.fi###frontPageCarContainer`

**Comment by peace2000** [comment]
Thank you for a suggestion but that's self-promotion which is not typically considered as an ad. Tori.fi is a platform to sell stuff and that banner is just showing some new stuff they have available. That banner could be considered as an annoyance but not as an ad. You can of course block that element in your own browser if you don't like it. :)
