### ISSUE TITLE
AdGuard now supports translations of 3rd-party list titles and descriptions. Do you have any wishes regarding such?

### ISSUE THREAD

**Issue by DandelionSprout** [finnish-easylist-addition/finnish-easylist-addition#262]
### List the website(s) you're having issues:

`https://crowdin.com/project/adguard-applications`

### What happens?

AdGuard has for some years now made it possible for translators to translate the titles and descriptions of AdGuard's own lists, and now they've apparently begun to allow it for included third-party lists as well, incl. Adblock List for Finland.

The two strings that AdGuard has opened up for translations of, are `Adblock List for Finland` and `Finnish ad blocking filter list.`

Do you have any wishes for how to translate them to Finnish, Swedish, and/or any other languages? And do you wish for the title (Adblock List for Finland) to be translatable, or that I should request to AdGuard that the title should be made untranslatable?

### List Subscriptions you're using:

N/A

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.193 x64
- Adblock Extension/version: uBO 1.30.9b16 + AdGuard for Windows 7.5.2 + I Don't Care About Cookies 3.2.4

### Other details:

![image](https://user-images.githubusercontent.com/22780683/99017561-8134c100-2558-11eb-973a-b9816230944d.png)

**Comment by peace2000** [comment]
Hi, thanks for asking. Had a busy weekend so that's why a late reply.

I don't think the title needs a translation, it's been in English since the beginning. And if the title is left in English it would be strange to translate the description. :D

**Comment by DandelionSprout** [comment]
Thanks for the feedback. I've now written about it as a comment to one of the strings on Crowdin.
