### ISSUE TITLE
hinta.fi

### ISSUE THREAD

**Issue by veikk0** [finnish-easylist-addition/finnish-easylist-addition#263]
### List the website(s) you're having issues:

`https://hinta/`

### What happens?

Small banner ads for MSI laptops appear at the top of the site.

### List Subscriptions you're using:

All built-in uBlock filters, EasyList, EasyPrivacy, [Malicious Online URL Blocklist](https://gitlab.com/curben/urlhaus-filter#urlhaus-malicious-url-blocklist), uBlock filters - Annoyances, Peter Lowe’s Ad and tracking server list, this filter list

### Your settings

Disabled all the extensions listed in the issue template.

- OS/version: Linux Mint 19 Tara 64-bit
- Browser/version: Firefox 83.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.31.0

### Other details:

Strangely enough, the ad only appears if the browser viewport is smaller than a certain value (for me it appears at about 965 pixels and below). Perhaps this is to make the banner appear mostly for mobile users?

![hinta-ad](https://user-images.githubusercontent.com/7808922/99954894-1ec79600-2d8c-11eb-825b-b3444c0a475e.png)

**Comment by peace2000** [comment]
Fixed in https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/ce6cf5fe7f1667973d691ed64aeb3549d4be6d5b
