### ISSUE TITLE
Ilta-Sanomat's videos won't load

### ISSUE THREAD

**Issue by krisu5** [finnish-easylist-addition/finnish-easylist-addition#264]
### List the website(s) you're having issues:
`https://www.is.fi/turun-seutu/art-2000007642522.html`, `https://www.is.fi/politiikka/art-2000007643142.html` (examples)

### What happens?
Video tries to load but when the loading icon disappears, video player stays blank. After disabling uBlock Origin, video loads again. Rarely, it does load the video with uBlock enabled too.

### List Subscriptions you're using:
- uBlock filters
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Resource abuse
- uBlock filters – Unbreak
- EasyList
- EasyPrivacy
- Online Malicious URL Blocklist
- Spam404
- AdGuard Annoyances
- FIN: Adblock List for Finland

### Your settings

- OS/version: Windows 10 Home, 2004 (my mom's computer, not mine :P)
- Browser/version: Firefox 83.0
- Adblock Extension/version: uBlock Origin, 1.31.0

**Comment by peace2000** [comment]
Hi, I also had this issue yesterday evening when I briefly tested it. However, now the issue seems to be gone. Do you still have this issue after you have updated your filter lists?

**Comment by krisu5** [comment]
In my setup that's more complex then my mom's, it does work again.

**Comment by peace2000** [comment]
Closing this as it works for now.
