### ISSUE TITLE
www.varusteleka.(fi|com) shopping cart

### ISSUE THREAD

**Issue by shnm** [finnish-easylist-addition/finnish-easylist-addition#265]
### List the website(s) you're having issues:
`https://www.varusteleka.com/en/cart`
`https://www.varusteleka.fi/fi/cart`

### What happens?
In the final steps of an order a customer has to accept the Terms and Conditions and Privacy Notice
Unfortunately the accept box is hidden by the `###privacypolicy` filter.
I fixed it locally in uBlock origin with the exception filter:
`varusteleka.fi#@##privacypolicy`

Could it be whitelisted in this filter list? I reported it to EasyList but not Adguard/Fanboy, don't have the time to register in their forums, sorry.

### Your settings
Broken atleast on:
AdGuard Annoyances
Fanboy’s Annoyance
EasyList Cookie

- OS/version: Windows 10 2004
- Browser/version: Firefox ESR / Chromium
- Adblock Extension/version: uBlock Origin

### Other details:
`###privacypolicy`

**Comment by peace2000** [comment]
Some screenshots, a mandatory checkbox is being removed:

![kuva](https://user-images.githubusercontent.com/17256841/101082620-659b6400-35b4-11eb-9441-a6d8e16652c9.png)

![kuva](https://user-images.githubusercontent.com/17256841/101082662-7946ca80-35b4-11eb-85fe-67c7d91af3d1.png)

**Comment by peace2000** [comment]
I'll a fix to this list until it's fixed in those other lists.

**Comment by peace2000** [comment]
It's fixed for this list so I'll close this for now. I made pull requests to Adguard and Easylist:

https://github.com/easylist/easylist/pull/6597
https://github.com/AdguardTeam/AdguardFilters/pull/69204

Fanboy's list uses The Easylist Cookie list as a component so it doesn't need separate fixing.
