### ISSUE TITLE
iltalehti.fi

### ISSUE THREAD

**Issue by lamtonylam** [finnish-easylist-addition/finnish-easylist-addition#269]
`iltalehti.fi`
### What happens?
Annoying newsletter popup comes up sometimes when browsing articles.
![image](https://user-images.githubusercontent.com/63186670/104235274-6b128680-545d-11eb-9b93-10994fb0f31d.png)

### Fix

![image](https://user-images.githubusercontent.com/63186670/104235667-fab83500-545d-11eb-9724-4d07a0906134.png)
`###il-newsletter-banner` Cosmetic filter

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/63186670/104235336-7fef1a00-545d-11eb-9f21-9f625f1c06b4.png)

- OS/version: Windows 10 latest
- Browser/version: Version 87.0.4280.141
- Adblock Extension/version: uBlock Origin 1.32.4

**Comment by peace2000** [comment]
You are seemingly not using the Finnish annoyance list so I assume you are asking to add this to the adblocking list? Adblocking list contains only adblocking rules so I added this to the Finnish Annoyance list https://raw.githubusercontent.com/finnish-easylist-addition/finnish-easylist-addition/master/annoyances/Finland_annoyances.txt
