### ISSUE TITLE
kinuskikissa.fi

### ISSUE THREAD

**Issue by DandelionSprout** [finnish-easylist-addition/finnish-easylist-addition#270]
### List the website(s) you're having issues:

`https://www.kinuskikissa.fi/laskiaispulla-hyydykekakku`

### What happens?

An ad for `DanSukker` near the top, and 2 placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/106519938-582f2700-64dc-11eb-9a12-b03911d03f01.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 88.0.4324.104 x64
- Adblock Extension/version: uBO 1.33.1b1 + I Don't Care About Cookies 3.2.7

### Other details:

I propose:
```
||kinuskikissa.fi/wp-content/uploads/*i_desk-*.gif^
kinuskikissa.fi##app-ad
```

![image](https://user-images.githubusercontent.com/22780683/106519800-25852e80-64dc-11eb-8b74-5ce384016a27.png)

**Comment by peace2000** [comment]
Thanks, I fixed it this way: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/29714acccbbaf982af368a110a48d9c3edfa7acc
