### ISSUE TITLE
bbs-io-tech.fi

### ISSUE THREAD

**Issue by The-Paavo** [finnish-easylist-addition/finnish-easylist-addition#271]
### List the website(s) you're having issues:

Io-tech forum (Xenforo)

### What happens?

Commit from yesterday (Feb 19, 2021) https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/59233f60682ce91f5ccc5fca0b078d1f069c9c24 removes "Liitä kuva" button from forum quick reply. Disabling this rule restores it. Offending rule is `io-tech.fi##body > div span > a[target="_blank"]`

Rule not enabled / Adguard

![Without](https://user-images.githubusercontent.com/1580135/108609613-bcf0e980-73d7-11eb-83ba-0b66d4309f38.png)

Rule enabled / Adguard

![With](https://user-images.githubusercontent.com/1580135/108609611-b8c4cc00-73d7-11eb-83e0-8045f89df3d2.png)

This affects at least all Adguard users, including mobile, but most likely others using this list too. Maybe a little bit too broadly defined rule?

**Comment by peace2000** [comment]
Quickfixed, disabled the bad rule now. This rule was not made for bbs.io-tech.fi, it was for www.io-tech.fi. I dropped the www-part, forgetting that bbs would also be affected.

**Comment by peace2000** [comment]
Made proper rules now. I think I'll retain the www part for this site from now on.
