### ISSUE TITLE
metsastysjakalastus.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#274]
### List the website(s) you're having issues:

`https://metsastysjakalastus.fi/`

### What happens?

Nagging about ad blocking.

![image](https://user-images.githubusercontent.com/84513173/118984838-94509f80-b986-11eb-877a-4b56937ce9e6.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Firefox 88.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

### Other details:

Blocking `metsastysjakalastus.fi##.DfpAdSlot_loading-parent` or `metsastysjakalastus.fi##.NoAdBlocker_main` should fix it.

**Comment by peace2000** [comment]
Fixed in https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/99a235e2ddb5309b8e02894f72292410c9a16244
