### ISSUE TITLE
kuvaton.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#277]
### List the website(s) you're having issues:

`https://www.kuvaton.com/`

### What happens?

Ads.

![image](https://user-images.githubusercontent.com/84513173/119421363-35cd4d80-bd07-11eb-9d6c-abcae1e99d8d.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Firefox 88.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

### Other details:

`kuvaton.com##.addme`
`kuvaton.com##[href^="https://www.kasinokaverit.com/"]`
`kuvaton.com##[href^="https://www.lainaovi.fi/"]`

**Comment by peace2000** [comment]
Added
