### ISSUE TITLE
io-tech.fi

### ISSUE THREAD

**Issue by DandelionSprout** [finnish-easylist-addition/finnish-easylist-addition#278]
### List the website(s) you're having issues:

`https://www.io-tech.fi/`

### What happens?

Banner on top.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/119778810-3a8d2f80-bec8-11eb-8f74-289d82e14527.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.77 x64
- Adblock Extension/version: uBO 1.35.3b5 + I Don't Care About Cookies 3.3.0

### Other details:

I propose `io-tech.fi##.box-container > span`, or alternately `/www/delvr^`

![image](https://user-images.githubusercontent.com/22780683/119778679-192c4380-bec8-11eb-9a36-564827df7443.png)

**Comment by Nojuuu** [comment]
`https://bbs.io-tech.fi/` has that too.

**Comment by Nojuuu** [comment]
`https://bbs.io-tech.fi/` has that too.

**Comment by Nojuuu** [comment]
`io-tech.fi##[href^="https://www.io-tech.fi/io/www/delvr/pick"]` seems to remove it from both.

**Comment by peace2000** [comment]
Fixed.

**Comment by Nojuuu** [comment]
@peace2000 banner seems to be back on `bbs.io-tech.fi`

**Comment by DandelionSprout** [comment]
From what I understand, I've been advised to keep new fix suggestions somewhat secret, due to the outstandingly high persuasion of `io-tech.io` at changing element names and possibly filenames to avoid blocking.

But I did send peace2000 some suggestions by E-mail some days ago, of which the first two should work for the forum.

**Comment by Perkolator** [comment]
The `io-tech.fi##body > div > div > span` rule seems to block site functionality. When selecting forum post text, a popup for "+ Lainaus" and "Vastaa" functions are not shown.

**Comment by peace2000** [comment]
Thanks for pointing out, it's disabled now.
