### ISSUE TITLE
finder.fi

### ISSUE THREAD

**Issue by DandelionSprout** [finnish-easylist-addition/finnish-easylist-addition#279]
### List the website(s) you're having issues:

`https://www.finder.fi/search?what=burger%20king`

### What happens?

Big placeholder on top.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/119778810-3a8d2f80-bec8-11eb-8f74-289d82e14527.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.77 x64
- Adblock Extension/version: uBO 1.35.3b5 + I Don't Care About Cookies 3.3.0

### Other details:

I propose `finder.fi##.Advertisement__Top`

![image](https://user-images.githubusercontent.com/22780683/119780490-2c401300-beca-11eb-96b7-0e5631fcb509.png)

**Comment by peace2000** [comment]
Added
