### ISSUE TITLE
kaksplus.fi

### ISSUE THREAD

**Issue by DandelionSprout** [finnish-easylist-addition/finnish-easylist-addition#280]
### List the website(s) you're having issues:

`https://kaksplus.fi/vauva/henriikka-reinman-30-poikkitilaraskauden-jalkeen-syytin-itseani-miksen-ole-onnellisempi-muuttuvasta-kehostani/`

### What happens?

Ad for shoes below the articles, including on articles that seemingly aren't about shoes.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/119778810-3a8d2f80-bec8-11eb-8f74-289d82e14527.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.77 x64
- Adblock Extension/version: uBO 1.35.3b5 + I Don't Care About Cookies 3.3.0 

### Other details:

I propose `||kaksplus.fi/upotukset/hintaopas^`

![image](https://user-images.githubusercontent.com/22780683/119780862-9b1d6c00-beca-11eb-893e-3b519f3856a5.png)

**Comment by peace2000** [comment]
Lol, didn't see that at first because I had Ubo's privacy list that blocked that element :D
