### ISSUE TITLE
fontanka.fi

### ISSUE THREAD

**Issue by DandelionSprout** [finnish-easylist-addition/finnish-easylist-addition#281]
### List the website(s) you're having issues:

`http://www.fontanka.fi/terveellista-ruokaa-grillaten/`

### What happens?

Two small placeholders on the right.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/119783190-47f8e880-becd-11eb-9507-732da8166c54.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.77 x64
- Adblock Extension/version: uBO 1.35.3b5 + I Don't Care About Cookies 3.3.0

### Other details:

I propose `fontanka.fi##.widget_custom_html`

![image](https://user-images.githubusercontent.com/22780683/119783774-d7060080-becd-11eb-81bf-5f772299e9d5.png)

**Comment by peace2000** [comment]
added
