### ISSUE TITLE
wizhdsports.fi

### ISSUE THREAD

**Issue by DandelionSprout** [finnish-easylist-addition/finnish-easylist-addition#282]
### List the website(s) you're having issues:

`https://wizhdsports.fi/rugby-on-kontaktilajien-suuri-kuningas/`

### What happens?

Two ad boxes on the right.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/119783190-47f8e880-becd-11eb-9507-732da8166c54.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.77 x64
- Adblock Extension/version: uBO 1.35.3b5 + I Don't Care About Cookies 3.3.0

### Other details:

I propose `wizhdsports.fi##.widget_media_image`

![image](https://user-images.githubusercontent.com/22780683/119784504-9064d600-bece-11eb-90af-067b91839368.png)

**Comment by peace2000** [comment]
Added
