### ISSUE TITLE
talouselama.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#284]
### List the website(s) you're having issues:

`https://www.talouselama.fi`

### What happens?

Ad placeholders.

![image](https://user-images.githubusercontent.com/84513173/120249027-252a5380-c282-11eb-8586-809ba1427ea3.png)
![image](https://user-images.githubusercontent.com/84513173/120249102-61f64a80-c282-11eb-8c0a-97c5742d9beb.png)
![image](https://user-images.githubusercontent.com/84513173/120249306-17290280-c283-11eb-8034-0681ea8bb09b.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 88.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

### Other details:

`talouselama.fi##.p2m385-5` would fix all for now but idk how long it would last?

**Comment by peace2000** [comment]
Good suggestion, though I modified a little bit :)

I also used Adblock Plus syntax because Ublock Origin supports it as well. (But not vice versa).
