### ISSUE TITLE
kaksplus.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#286]
### List the website(s) you're having issues:

`https://kaksplus.fi/`

### What happens?

Ad placeholders again.

![image](https://user-images.githubusercontent.com/84513173/121628735-7efcfb80-ca82-11eb-9a88-648767935c68.png)
![image](https://user-images.githubusercontent.com/84513173/121628895-cf745900-ca82-11eb-9fae-03a8a9ca7b72.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

### Other details:

`kaksplus.fi##.widget_nativearticles`
`kaksplus.fi##.placeholder`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/fb685348a2615974ae6480424b21cd392030769b
