### ISSUE TITLE
suomikiekko.com, suomikoris.com, suomif1.com, suomiurheilu.com, suomifutis.com, eurheilu.org  + a lot more

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#288]
### List the website(s) you're having issues:

`https://www.suomikiekko.com`
`https://www.suomikoris.com`
`https://www.suomif1.com`
`https://www.suomiurheilu.com`
`https://www.suomifutis.com`
`https://eurheilu.org`
`https://www.susijengi.com`
`https://www.valioliiga.com/`
`https://www.leijonat.com/`
`https://www.arvokisat.com/`
`https://www.laliiga.com/`
`https://www.nhlsuomi.com/`

### What happens?

Same casino/betting ads under article on all those sites.

![image](https://user-images.githubusercontent.com/84513173/121785976-bfb15d80-cbc5-11eb-8299-4e32f9ceacba.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

### Other details:
`suomikiekko.com,suomikoris.com,suomif1.com,suomiurheilu.com,suomifutis.com,eurheilu.org,susijengi.com,valioliiga.com,leijonat.com,arvokisat.com,laliiga.com,nhlsuomi.com##.td-post-content > hr ~ ul, .td-post-content > hr ~ p, .td-post-content > hr ~ h3`

Maybe?

**Comment by Nojuuu** [comment]
Or just `suomikiekko.com,suomikoris.com,suomif1.com,suomiurheilu.com,suomifutis.com##.td-post-content > hr ~ *`

**Comment by Nojuuu** [comment]
Also on `https://www.herkkusuut.com` and `sketsi.net` 

`herkkusuut.com##.single-post-content > hr ~ *`
`sketsi.net##.td-post-text-content > hr ~ *`

Could also just drop that container element and do  
`allsiteslistedhere##hr ~ p, hr ~ h3, hr ~ ul`
or
`allsiteslistedhere##hr ~ *`

**Comment by peace2000** [comment]
Let's go with this: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/e7c6988ed258a144519ed932768426eb2af0ab2e

**Comment by Nojuuu** [comment]
@peace2000 

At least some of these sites also seem to have ad placeholders above the article on mobile devices.

Line 121 has `##.tdt-desktop-ad`, could you try changing it to `##.tdt-parade-ad`? I think it should handle both desktop and mobile ads. 

But if it causes problems, you can add `##.tdt-mobile-ad`.

**Comment by peace2000** [comment]
`##.tdt-parade-ad` does block the placeholder at the top but `##.tdt-mobile-ad` will also match an element after the article. Blocking that element will remove some of the white space area so I think I'll use both of them. https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/4ebcead49b0f71ad60d5ce991bdd4ff20aebd4df

Adding `##.tdt-parade-ad` does not seem to necessary as it's being only used by this site cluster and is covered by desktop and mobile -rules:

Source code search engine results:

https://publicwww.com/websites/%22tdt-parade-ad%22/

https://www.nerdydata.com/reports/tdt-parade-ad/7474354e-6dd9-4222-84d5-4f7212f3f344

I'll let `##.tdt-desktop-ad` and `##.tdt-mobile-ad` be generic rules even though they are not seemingly being used outside of this site cluster either, site specific rule would be pretty long anyway and they sound generic too. :P
