### ISSUE TITLE
metropoli.net

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#289]
### List the website(s) you're having issues:

`https://www.metropoli.net/`

### What happens?

Ad placeholders

![image](https://user-images.githubusercontent.com/84513173/121790707-b090d680-cbea-11eb-80d1-692fe4b0ded9.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

### Other details:

`www.metropoli.net##.ads-desktop`

`www.metropoli.net##.ads-mobile`
**I wouldn't put this one as mobile specific rule, appears on desktop when window width is ~980px.**

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/a85d0c3884615aae76c84fb658720fdaf250fddc
