### ISSUE TITLE
koneviesti.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#290]
### List the website(s) you're having issues:

`https://www.koneviesti.fi/`

### What happens?

Ad

![image](https://user-images.githubusercontent.com/84513173/122321908-48fdc280-cf2d-11eb-9073-6d48b43c759c.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

**Comment by Nojuuu** [comment]
Also consider adding `koneviesti.fi##.promo`, removes ad placeholders.

**Comment by peace2000** [comment]
fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/ec25e29e215b3b6c3c721c77557a87df8facec12

**Comment by Nojuuu** [comment]
`maaseuduntulevaisuus.fi#?#div[class="col-large-12 col-medium-12 col-small-12"]:-abp-has( > div > a > div[class="article__sp-aside-list__heading"]):-abp-contains(Mainos)`

I think you removed that one with this fix. It should be added back and add `koneviesti.fi` to it too because it removes that ad when window width is smaller.

**Comment by peace2000** [comment]
Thanks pointing out. I made a different kind of rule because I wanted to simplify it. I now made a small change to my rule https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/0c1b5a2d19a4c3ad170713f00b16efd4fa7f726a which seems to fix it for both deskop and mobile.
