### ISSUE TITLE
tennis.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#291]
### List the website(s) you're having issues:

`https://www.tennis.fi/`

### What happens?

Ads

![image](https://user-images.githubusercontent.com/84513173/122327909-59b33600-cf37-11eb-8cf2-ff0bd3917aab.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

### Other details:

`tennis.fi##.ad-blocks`

**Comment by peace2000** [comment]
fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/ec25e29e215b3b6c3c721c77557a87df8facec12
