### ISSUE TITLE
teknavi.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#293]
### List the website(s) you're having issues:

`https://teknavi.fi/`

### What happens?

Ad placeholders

![image](https://user-images.githubusercontent.com/84513173/122655831-4a620180-d15e-11eb-966d-4cd25d21f9d1.png)
![image](https://user-images.githubusercontent.com/84513173/122655861-944ae780-d15e-11eb-8f48-5955d3d72a6e.png)
![image](https://user-images.githubusercontent.com/84513173/122655875-b0e71f80-d15e-11eb-8600-1e1d304808b9.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

### Other details:

`teknavi.fi##.ad`
`teknavi.fi##[class^="adform"]`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/b518e0986716b847b4af52096bdb9e0b5b53819a
