### ISSUE TITLE
suomimobiili.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#294]
### List the website(s) you're having issues:

`https://suomimobiili.fi/`

### What happens?

Sponsored ad articles 

![image](https://user-images.githubusercontent.com/84513173/122680789-aded3d00-d1f9-11eb-8750-ac4fe9c273f5.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

### Other details:

Maybe `suomimobiili.fi##.module-square-grid:-abp-contains(Artikkeleita kumppaneilta)` or `suomimobiili.fi##.module-square-grid:-abp-contains(Sponsoroitu)` ?

**Comment by Nojuuu** [comment]
Also one in the article listing slightly above these

![image](https://user-images.githubusercontent.com/84513173/122681169-c3fbfd00-d1fb-11eb-93e0-87eb4b1e5b19.png)

**Comment by peace2000** [comment]
In order to block them with one rule, I'll go with `suomimobiili.fi#?#.content-wrap > .bkmodule:-abp-contains(Sponsoroitu)`

(Rules that use -abp- syntax must have a question mark between hashtags #?# so that ABP can read that rule. Ubo accepts both versions but not ABP.)

**Comment by Nojuuu** [comment]
> (Rules that use -abp- syntax must have a question mark between hashtags #?# so that ABP can read that rule. Ubo accepts with or without question mark but not ABP.)

Ok, good to know 👍
