### ISSUE TITLE
nettivaraosa.com, nettiauto.com etc.

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#295]
### List the website(s) you're having issues:

`m.nettivaraosa.com` | `www.nettivaraosa.com`
`m.nettimarkkina.com` | `www.nettimarkkina.com`
`m.nettikaravaani.com` | `www.nettikaravaani.com`
`m.nettiauto.com` | `www.nettiauto.com`
`m.nettimokki.com` | `www.nettimokki.com`
`m.nettivene.com` | `www.nettivene.com`
`m.nettikone.com` | `www.nettikone.com`
`www.nettimoto.com`

### What happens?

Ad placeholders, banners

![image](https://user-images.githubusercontent.com/84513173/122805788-33dcb700-d2d2-11eb-9568-3866b1c1c19e.png)

![image](https://user-images.githubusercontent.com/84513173/122806224-bf564800-d2d2-11eb-8e63-47b6f0d3f4d1.png)

![image](https://user-images.githubusercontent.com/84513173/122807080-ccc00200-d2d3-11eb-867b-a7a07be3d821.png)

![image](https://user-images.githubusercontent.com/84513173/122807640-815a2380-d2d4-11eb-8601-33e3b5e8dea2.png)

![image](https://user-images.githubusercontent.com/84513173/122809518-df880600-d2d6-11eb-9b96-cf2fbd4c366a.png)

![image](https://user-images.githubusercontent.com/84513173/122810650-4528c200-d2d8-11eb-8211-3682ca00609e.png)

![image](https://user-images.githubusercontent.com/84513173/122815976-d13de800-d2de-11eb-9734-61ce6034cdbd.png)

![image](https://user-images.githubusercontent.com/84513173/122816833-e404ec80-d2df-11eb-8ccd-acf8116dbeff.png)

![image](https://user-images.githubusercontent.com/84513173/122817597-c6845280-d2e0-11eb-88b6-301a983cb073.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

### Other details:

**First image:**
`m.nettikone.com,m.nettivaraosa.com,m.nettikaravaani.com,m.nettimarkkina.com,m.nettiauto.com,m.nettimokki.com,m.nettivene.com##.topBannerMinHeight`
Ad placeholder.

**Second image:**
`m.nettikone.com,m.nettivaraosa.com,m.nettikaravaani.com,m.nettivene.com###banner_area`
Might be possible that this can appear on all of these sites but saw only on these.

**Third image:**
`nettikaravaani.com,nettivene.com##.leftAdvDiv`
Removes grey placeholder box. This can probably also appear on other sites too.
Also seems to already be blocked on some of these site.

**Fourth image:**
`m.nettikone.com,m.nettivaraosa.com,m.nettikaravaani.com,m.nettimarkkina.com,m.nettimokki.com##[class*="dfpTopBanner"]`
This appears when you search something. className not consistent on all sites (dfpTopBanner, dfpTopBanner1, dfpTopBanner-1 etc.)
Saw only on these sites when I was investigating but very likely can occur on other sites too.

**Fifth image:**
`m.nettikone.com,m.nettikaravaani.com,m.nettimokki.com#?#li:-abp-has(.banner)`
Also when you search something. Probably on other sites too.

**Sixth image:**
`m.nettikone.com,m.nettivaraosa.com,m.nettikaravaani.com##.lazyLoadInhouseBanner`
Probably on other sites too.

**Seventh image:**
`nettimoto.com###largeViewHouseBanner`
Probably on other sites too.

**Eighth image:**
`nettimoto.com##.quick-search__banner`

**Ninth image:**
`nettimarkkina.com###vif_right_banner`
Ad placeholder.

**Comment by peace2000** [comment]
Fixed numbers 1-4. Will check others later. https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/6363e7eb1c21bde8e518d419a75775995402d361

I think the best (and easiest) way to manage this is to use all-in-one type rules where all domains are listed even though not every single of those domains use specific ads.

Also added a couple of generic hiding rules:

`##[class^="dfp"]`
`##[id^="dfp"]`

Because element names that begin with "dfp" are being used on many other sites as well.

**Comment by peace2000** [comment]
Ok, should be good now. https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/f5ebbc2be1b97cdfa3a10a5e48a3544c283fdace

**Comment by Nojuuu** [comment]
Found one more on `nettimoto.com`

![image](https://user-images.githubusercontent.com/84513173/123024177-4f82b300-d3e1-11eb-85c5-18eeb27633a2.png)

**Comment by Nojuuu** [comment]
@peace2000 

Also seems like we need something better than `#?#li:-abp-has(.banner)`, that works fine on desktop but on mobile it does this:

https://user-images.githubusercontent.com/84513173/123051013-fa0ecc00-d409-11eb-99f5-c3fa60d9ecbf.mp4

**Comment by peace2000** [comment]
> 
> 
> Found one more on `nettimoto.com`
> 
> ![image](https://user-images.githubusercontent.com/84513173/123024177-4f82b300-d3e1-11eb-85c5-18eeb27633a2.png)

Where that can be found? I don't see that ad. Can you give an exact link?

**Comment by peace2000** [comment]
> 
> 
> @peace2000
> 
> Also seems like we need something better than `#?#li:-abp-has(.banner)`, that works fine on desktop but on mobile it does this:
> 34b35b3w.-.Copy.2.mp4
> 
> E: `#?#.pb10.pt10:-abp-has(.banner)` doesn't seem to have that problem but not sure if that works for all sites.
> 
> Also just doing `.pb10.pt10` should be even faster but not sure if it's used only for ads or if it is used on all sites.

Made a faster filter: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/b21a29551c3044428772aea69a54d4eaf843cade

**Comment by Nojuuu** [comment]
> Where that can be found? I don't see that ad. Can you give an exact link?

`https://www.nettimoto.com/polaris/sportsman/2676684`

Can you see it there? It doesn't always show up.

**Comment by peace2000** [comment]
> 
> 
> > Where that can be found? I don't see that ad. Can you give an exact link?
> 
> `https://www.nettimoto.com/polaris/sportsman/2676684`
> 
> Can you see it there slightly below the product? It doesn't always show up.
> 
> In case you cant see it, you can search for `smallViewHouseBanner` in dev tools and you should be able to see where it sometimes appears.

It seems to be visible when the desktop site is being used but when the browser window is small enough.

**Comment by Nojuuu** [comment]
@peace2000 

Btw, I also opened this issue couple of days ago if you want to fix it here until it's fixed in Easylist Cookie.

https://github.com/easylist/easylist/issues/8160

**Comment by peace2000** [comment]
@Nojuuu  Yeah, added: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/b66a2105b23dcc3fab070c8413fa87d675eb506a

**Comment by peace2000** [comment]
These seem to block that banner without causing issues with pictures:

```
nettivuokraus.com##+js(aeld, load, function J)
nettivuokraus.com##+js(aeld, message, function(i))
```
