### ISSUE TITLE
kestavyysurheilu.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#296]
### List the website(s) you're having issues:

`https://www.kestavyysurheilu.fi/`

### What happens?

Ads

![image](https://user-images.githubusercontent.com/84513173/123553147-3c296c00-d782-11eb-99ca-7bc202345f60.png)
![image](https://user-images.githubusercontent.com/84513173/123553198-75fa7280-d782-11eb-8913-cf40012176b5.png)
![image](https://user-images.githubusercontent.com/84513173/123553176-59f6d100-d782-11eb-9089-737d59b43632.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.0

### Other details:

`kestavyysurheilu.fi##.middleads`
`kestavyysurheilu.fi#?#.moduleBox:-abp-contains(Kaupalliset yhteistyöt)`
`kestavyysurheilu.fi###precont`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/a3a1ac0edb7471abf7b875e61548358bf8111111
