### ISSUE TITLE
rantapallo.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#297]
### List the website(s) you're having issues:

`https://www.rantapallo.fi/`

### What happens?

Ad

![image](https://user-images.githubusercontent.com/84513173/123553868-333a9980-d786-11eb-88fb-5d21fb48d51b.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.0

### Other details:

`rantapallo.fi##.ad-empty`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/2ad30f5bfff0a695752f48d7f8662ca76809b4ab
