### ISSUE TITLE
aromilehti.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#298]
### List the website(s) you're having issues:

`https://aromilehti.fi/`

### What happens?

Ad + placeholder

![image](https://user-images.githubusercontent.com/84513173/123554513-063bb600-d789-11eb-81d8-db591958d8d0.png)
![image](https://user-images.githubusercontent.com/84513173/123554250-bdcfc880-d787-11eb-846f-63c32178d1a7.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.0

### Other details:

`aromilehti.fi##.ad`
`aromilehti.fi##.ad-paper-order`

**Comment by peace2000** [comment]
`##.ad-paper-order` is at least something that should be blocked. But I don't feel that gala-stuff should be considered as an ad, even though it's element name says so. I feel it's more like self promotion as that event is related to the topic of that site.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/15b073d4ceb7e758683c198cd03dbb99ef8ec645
