### ISSUE TITLE
olutposti.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#299]
### List the website(s) you're having issues:

`https://olutposti.fi/`

### What happens?

Ad placeholders

![image](https://user-images.githubusercontent.com/84513173/123554607-76e2d280-d789-11eb-9a96-6da1bd6aebe1.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.0

### Other details:

`olutposti.fi#?#.aside.widget:-abp-contains(Mainos)`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/fbc9eb249c76a1e2f2d9f3b065174b1b4b6b8876
