### ISSUE TITLE
mobiili.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#300]
### List the website(s) you're having issues:

`https://mobiili.fi/`

### What happens?

Sponsored ad articles.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.0

### Other details:

There's already this rule:
`mobiili.fi#?#div.fullarticle:-abp-has(img[src="https://mobiili.fi/aaa.png"])`
 but because that is lazyloaded, it doesn't work alone.

You need to add this:
`mobiili.fi#?#div.fullarticle:-abp-has([data-lazy-src="https://mobiili.fi/aaa.png"])`
but don't remove that other rule, because this isn't always fast enough to work alone.

Or if you want to handle it with one rule, you can do this:
`mobiili.fi#?#div.fullarticle:-abp-has(.categories img)` (other categories are `<a>` tags)
but it is less specific and could cause problems later.

**Comment by peace2000** [comment]
That site does work indeed strangely, sometimes `mobiili.fi#?#div.fullarticle:-abp-has([data-lazy-src="https://mobiili.fi/aaa.png"])` gets matches and sometimes it doesn't. I guess I'll add it so adblocking will work better. https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/c9abcf6e6e8430ff6aacba7e9e2aecb4bc6bbe15

**Comment by Nojuuu** [comment]
Still seeing these on Chromium based browsers.

Replace both filters with this:
`mobiili.fi#?#.fullarticle:-abp-has(.categories > img)`

**Comment by peace2000** [comment]
I noted one day that `mobiili.fi#?#div.fullarticle:-abp-has([data-lazy-src="https://mobiili.fi/aaa.png"])` works badly. Sample page to test with: https://mobiili.fi/2021/08/

I even reported it as an issue https://github.com/uBlockOrigin/uBlock-issues/issues/1686 but it wasn't a bug, just needs a different kind of filter.

`mobiili.fi#?#.fullarticle:-abp-has(.categories > img)` sounds bit too generic, even though it works. I'll have to think this...

**Comment by peace2000** [comment]
Maybe `mobiili.fi#?#.fullarticle:-abp-has(.categories > img[class=lazyloaded])`, I'll test more when I have time.

**Comment by Nojuuu** [comment]
> 
> 
> Maybe `mobiili.fi#?#.fullarticle:-abp-has(.categories > img[class=lazyloaded])`, I'll test more when I have time.

I tried it and it didn't seem to work. but this one did:
`mobiili.fi#?#.fullarticle:-abp-has(.categories > img[width="66"][height="18"])`

**Comment by Nojuuu** [comment]
`mobiili.fi#?#.fullarticle:-abp-contains(src="https://mobiili.fi/aaa.png")` this also works :D

**Comment by Nojuuu** [comment]
> I noted one day that `mobiili.fi#?#div.fullarticle:-abp-has([data-lazy-src="https://mobiili.fi/aaa.png"])` works badly. Sample page to test with: https://mobiili.fi/2021/08/

It seems to work when I have it in "My Filters", but not when loaded from the filter list? I noticed that I had never removed it from my own filters, so that's why I never noticed a problem on this site with Firefox, but now when I remove it, the same problem occurs there too.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/e7df42fedbf920a065dcc432ecd3e570a9cdd9b8

How does that work when you update your lists?

**Comment by Nojuuu** [comment]
> How does that work when you update your lists?

It seems to be working fine.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/58bf0487c868725595c8044a08261a7923760b3b added better filter for Firefox.

**Comment by Nojuuu** [comment]
![image](https://user-images.githubusercontent.com/84513173/132057437-50ead01e-5cae-4ccb-b7b0-4304fae8fa2d.png)

```
mobiili.fi##.tops-bar
```

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/f3cf35f792aee99233f1321a03305773b45220e6
