### ISSUE TITLE
gamereactor.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#301]
### List the website(s) you're having issues:

`https://www.gamereactor.fi/`

### What happens?

Ad placeholders.

![image](https://user-images.githubusercontent.com/84513173/123908423-241f3b80-d980-11eb-9c19-9534c11aceac.png)
![image](https://user-images.githubusercontent.com/84513173/123908479-4022dd00-d980-11eb-8952-3c89718ede74.png)
![image](https://user-images.githubusercontent.com/84513173/123908559-5af55180-d980-11eb-828a-3a33355d32c3.png)
![image](https://user-images.githubusercontent.com/84513173/123908629-72ccd580-d980-11eb-96e9-00fab90838e2.png)
![image](https://user-images.githubusercontent.com/84513173/123908680-85dfa580-d980-11eb-86c8-696a2d9e5c57.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.0

### Other details:

```
!#if env_mobile
gamereactor.fi###ad_sticky
gamereactor.fi#?#.wrapper:-abp-has(.ad_interscroller)
gamereactor.fi#?#[style*="text-transform: uppercase;"]:-abp-contains(Tämä on mainos:)
gamereactor.fi##[class^="ad_mobileLeader"]
gamereactor.fi##[class^="ad_smartphbig"]
!#endif
```

You also need to set up remote debugging if you want to try to figure out better filters because it serves a different version of the site on your actual mobile device.

**Comment by Nojuuu** [comment]
![image](https://user-images.githubusercontent.com/84513173/123911288-44e99000-d984-11eb-955e-f0b99cde3154.png)

`gamereactor.fi##.sponsor`

**Comment by peace2000** [comment]
Where is ##.videoAd element? I cannot find it.

**Comment by peace2000** [comment]
Added others: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/70171b53ada74a6dfe8dd38712de6607242192ca I didn't want to use -abp-has -rules due to recent issues that syntax had on mobile recently as you probably remember.

**Comment by Nojuuu** [comment]
>Where is `##.videoAd` element? I cannot find it.

`https://www.gamereactor.fi/ennakko/` there should be one.

**Comment by peace2000** [comment]
Thanks, added that too. https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/fe90e6e7f7352f49c9049b625b3c66a537dd635e

**Comment by Nojuuu** [comment]
There seems to be one more "TÄMÄ ON MAINOS" text at the top on `https://www.gamereactor.fi/ennakko/`

**Comment by peace2000** [comment]
And another one at the bottom... lol.

I shortened the style rule to block those, I think it's still safe. https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/23d42fadf990a55b20ea9266e8292591cfe77614

**Comment by Nojuuu** [comment]
`https://www.gamereactor.fi/ennakko/854603/Humankind+uusi+katsaus+Amplitude+Studiosin+taidonnaytteeseen/` that 
wrapper for .ad_interscroller seems to also appear in articles. 

After that I think everything should be fine.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/1a9b306c2c5451767c7c264f172893bf0eb45d86

**Comment by peace2000** [comment]
As a bonus I added a html filter for Firefox users https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/7a206ab0a08b6dd2d88ae008175ac7aa5e410a76 it will remove the top bar before the site loads, so there will be no blink of it. I saw a blink when I F5'd the page many times.

**Comment by Nojuuu** [comment]
> 
> 
> [1a9b306](https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/1a9b306c2c5451767c7c264f172893bf0eb45d86)

Needs to be just `.wrapper` instead, if you dont want to use -abp-has

**Comment by peace2000** [comment]
Seems I got something wrong...

Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/36e25f66574337cdb2a52cef9635c271c41c152e

**Comment by Nojuuu** [comment]
I could have explained it more clearly, I tried to refer to the rule in my original post, but now everything seems to be good. 👍

**Comment by Nojuuu** [comment]
@peace2000 

![image](https://user-images.githubusercontent.com/84513173/125143723-3c334f80-e124-11eb-97c0-7554751a43b4.png)

This shows up occasionally on the desktop, and it looks like there's already a rule for it, but it seems to be for mobile only.

**Comment by peace2000** [comment]
I can reproduce but i'm bit confused, that didn't show up very recently for desktop...

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/f9cc423c1813be0b0156669cfeb0f5f40c52eb99
