### ISSUE TITLE
napsu.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#302]
### List the website(s) you're having issues:

`https://www.napsu.fi/`

### What happens?

Ad placeholder

![image](https://user-images.githubusercontent.com/84513173/124227598-9ffdbd00-db13-11eb-84e3-3eaa97ed8e60.png)
.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.0

### Other details:

`napsu.fi##.mobilead`

Not just for mobile. Appears when window width is less than 1000px.

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/39cbc4a4e006bf77afee328a301cb6e06a4b038a
