### ISSUE TITLE
apteekkari.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#303]
### List the website(s) you're having issues:

`https://www.apteekkari.fi/uutiset/farmasian-opetus-hakee-vauhtia-virtuaalitodellisuudesta`

### What happens?

Ad in the middle of every article

![image](https://user-images.githubusercontent.com/84513173/124579138-86cc7780-de57-11eb-9a46-51f50533ed21.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.0

### Other details:

`||cds.*.hwcdn.net^$script,domain=apteekkari.fi`

or

`apteekkari.fi#?#.container:-abp-contains(MAINOS (TEKSTI JATKUU ALLA))`

**Comment by peace2000** [comment]
`||cds.*.hwcdn.net^$script,domain=apteekkari.fi`

Works only for Firefox, as it's cname related stuff. Chrome does not support that... I'll add both of them as script blocking is better, at least Firefox users will benefit.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/b5066824a1e8681855a66d069f499c9dca39e34d
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/fdd55977f8443f195614a4cc0c19c5e214dc4d65

**Comment by Nojuuu** [comment]
@peace2000 
> 
> 
> `||cds.*.hwcdn.net^$script,domain=apteekkari.fi`
> 

I noticed that it also breaks this:
![image](https://user-images.githubusercontent.com/84513173/133256187-b5799921-0f91-49de-846f-1415ea941112.png)


However we can replace it with this so at least the images wont load: `||apteekkari.fi/media/kuvat/mainokset/*^$all`

There's also ads in that thing:
![image](https://user-images.githubusercontent.com/84513173/133256755-16e43d38-1f18-4219-bd31-82d9356e5766.png)


`apteekkari.fi##.native-comms`

**Comment by peace2000** [comment]
Removed CNAME filter https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/ef0d14813d7a0c091656674642192210aadc4399. This `||apteekkari.fi/media/kuvat/mainokset/*^$image` is already covered by `/mainokset/*`.

Am I missing something, as this filter `||apteekkari.fi/media/kuvat/bannerit/*^$image` shows no hits in logger?

Added `apteekkari.fi##.native-comms` https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/390fbc8a5ac7f1ac1dd7977bee701ff180a7bca2

**Comment by Nojuuu** [comment]
Sometimes that ad in the middle of article is served from `/bannerit/` instead of `/mainokset/`. I'll try to find example again if I can.

**Comment by Nojuuu** [comment]
`https://www.apteekkari.fi/uutiset/apteekkariliitto-kirittaa-apteekkialan-uudistuksia.html`

![image](https://user-images.githubusercontent.com/84513173/133336324-6cd04be4-4835-4024-a7d1-4e37daf859d3.png)

**Comment by peace2000** [comment]
I actually found just one link too: `https://www.apteekkari.fi/uutiset/seisominen-voi-auttaa-ehkaisemaan-tyypin-2-diabetesta-ja-sydantauteja`

https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/9105e975e6be84a80ede24007b0b7dd716566054
