### ISSUE TITLE
koillissanomat.fi, iijokiseutu.fi etc.

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#304]
### List the website(s) you're having issues:

`https://www.koillissanomat.fi/`
`https://www.iijokiseutu.fi/`
`https://www.siikajokilaakso.fi/`
`https://www.pyhajokiseutu.fi/`
`https://www.rantalakeus.fi/`

All of these are Kaleva Media sites, so if I missed a site where this occurs you can find list of the sites here at the bottom:
`https://www.kalevamedia.fi/`

Also these were already in the filter list:
`kaleva.fi###paraati-ad-grid`
`lapinkansa.fi###paraati-ad-grid`
`raahenseutu.fi##[id="paraati-ad-grid"]`

### What happens?

Ad placeholder

![image](https://user-images.githubusercontent.com/84513173/124581095-75846a80-de59-11eb-8b4c-71e7b9f92d89.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.0

### Other details:

`iijokiseutu.fi,koillissanomat.fi,pyhajokiseutu.fi,rantalakeus.fi,siikajokilaakso.fi###paraati-ad-grid`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/19138a662a1a06c37fb26379eb4e94c747998f77
