### ISSUE TITLE
pelaaja.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#306]
### List the website(s) you're having issues:

`https://pelaaja.fi/`

### What happens?

"Kuuminta nyt/Nyt arvostelussa" link in the yellow box under navbar is broken if you have EasyPrivacy enabled because it blocks Google Analytics.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.0

### Other details:

This is what it tries to do on click:

```
function(event) {
  var url = event.target.href;
  if (!ga) {
    return;
  }

  event.preventDefault();

  ga('send', {
    hitType: 'event',
    eventCategory: 'Ticker',
    eventAction: 'click',
    eventLabel: url,
    transport: 'beacon',
    hitCallback: function() {
      document.location = url;
    },
  });
}
```

___________

At least on uBO this seems to fix it:
`pelaaja.fi##+js(aopr, ga)`

**Comment by peace2000** [comment]
Added whitelisting for all adblockers https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/6994088d08eaaa9664195fca50ab2a14dcb00328

But fix for Ubo: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/6d78caad0472968aa8a3e973bbf5611b28303e14

And pull request for main Easylist: https://github.com/easylist/easylist/pull/8317
