### ISSUE TITLE
tekniikkatalous.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#308]
### List the website(s) you're having issues:

`https://www.tekniikkatalous.fi/`

### What happens?

Ad placeholders

![image](https://user-images.githubusercontent.com/84513173/125291088-b123a680-e329-11eb-9ecc-25b424cc1e26.png)
![image](https://user-images.githubusercontent.com/84513173/125292112-cbaa4f80-e32a-11eb-93de-1ccdbee1de36.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

`tekniikkatalous.fi#?#[width]:-abp-has(.lazyload-wrapper)`

**Comment by Nojuuu** [comment]
@peace2000  

Same issue on  uusisuomi.fi but filter should be
`##[width]:has(.lazyload-wrapper):not(aside)`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/ad636028812a108c92118d150e8290cc1d3f49d0
