### ISSUE TITLE
aitiydenihme.fi, askelterveyteen.com, mielenihmeet.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#309]
### List the website(s) you're having issues:

`https://aitiydenihme.fi/`
`https://askelterveyteen.com/`
`https://mielenihmeet.fi/`

### What happens?

Ad placeholders

![image](https://user-images.githubusercontent.com/84513173/125795048-d3071e25-16b2-45a3-a8c1-425f2725b686.png)
![image](https://user-images.githubusercontent.com/84513173/125793487-7abb4b7d-d070-4c91-9ff9-0e795e77d9b7.png)
![image](https://user-images.githubusercontent.com/84513173/125794697-159b15c5-492b-454a-9471-06acb24f0d30.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

`aitiydenihme.fi,askelterveyteen.com,mielenihmeet.fi##.ads__container`
`aitiydenihme.fi,askelterveyteen.com,mielenihmeet.fi##.card-article-ads`

**Comment by Nojuuu** [comment]
Also at https://myanimals.com/fi/, but idk if it should be addressed here, since that site defaults to an English version?

**Comment by peace2000** [comment]
I think those should be added as a generic filters to the main Easylist: https://github.com/easylist/easylist/pull/8360

Added them to the Finnish list until they are added to the main list: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/b31a2e6b273efb0f12b78bcb3d9c6b515dc5a8ba
