### ISSUE TITLE
kauppalehti.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#310]
### List the website(s) you're having issues:

`https://www.kauppalehti.fi/`

### What happens?

Ad placeholders

![image](https://user-images.githubusercontent.com/84513173/125822605-7a73ff6a-0644-4c7d-92e3-3348ca7554d9.png)
![image](https://user-images.githubusercontent.com/84513173/125822312-74b04385-c416-453b-ae6b-f520fa70dd56.png)
![image](https://user-images.githubusercontent.com/84513173/126036431-aa20b628-3ef7-4049-b199-92ed9231f7f9.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

`kauppalehti.fi#?#[width]:-abp-has(.ad):not(aside)`

**Comment by Nojuuu** [comment]
Adding :upward(1) to that would be even better as it also removes useless divs around that element, but I think only uBO supports it properly?

**Comment by peace2000** [comment]
ABP doesn't support `updard()` selector or even anything similar: https://adblockplus.org/filter-cheatsheet#elementhideemulation it's extended filters are pretty limited, `nth-ancestor` didn't work either.

I don't have experience on writing xpath filters.

But doesn't this rule do the trick?

kauppalehti.fi#?#div:-abp-has( > div[width] > .ad:not(aside))

**Comment by Nojuuu** [comment]
> Doesn't this rule do the trick?
> 
> `kauppalehti.fi#?#div:-abp-has( > div[width] > .ad:not(aside))`

Yeah, seems to work.

**Comment by peace2000** [comment]
Yes, I noticed it looked easy in Ubo but when it comes to ABP... So we'll have to go with `kauppalehti.fi#?#div:-abp-has( > div[width] > .ad:not(aside))`

Or actually with `kauppalehti.fi#?#div:-abp-has(> div[width] > .ad:not(aside))` as ABP does not accept a space between ( and >...

Just noticed. https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/fa37be084e3d11899a578d442f22b4a0c7f11ac4

**Comment by Nojuuu** [comment]
@peace2000 

same issue now on `https://www.arvopaperi.fi/`

**Comment by peace2000** [comment]
Fixed that too https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/614094d4a4e2e50ae341b4afbc67af716f14bc15

**Comment by Nojuuu** [comment]
@peace2000 They changed something and now this filter also hides articles when window width is smaller than 770px...

**Comment by peace2000** [comment]
Removed issue rule https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/219850c16601fdd23ff166bea95171c99621524b

**Comment by peace2000** [comment]
`kauppalehti.fi#?#div[class]:not(#article-content):-abp-has( > div[class][width] > .ad)`
`kauppalehti.fi#?#div[class][width]:-abp-has(> .ad)`

I added `[class]` and `:not(#article-content)` to make it more specific and safe. I want to hide parent element of `div[class][width]` also to remove some white areas.

The second rule is to block empty ad container inside articles when screen width is small.
