### ISSUE TITLE
traktorpool.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#311]
### List the website(s) you're having issues:

`https://www.traktorpool.fi/`

### What happens?

Ad placeholder

![image](https://user-images.githubusercontent.com/84513173/126046989-b019f9f2-0a78-456c-b238-d1d2ef4d14cb.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

`traktorpool.fi##.billboard`
or
`traktorpool.fi#?#.billboard:-abp-has([id|="div-gpt-ad"])`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/028bc5c8dd5d9f824f5c6c2f9354019a440dbfcc
