### ISSUE TITLE
episodi.fi, fum.fi, inferno.fi, como.fi, soundi.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#312]
### List the website(s) you're having issues:

`https://www.episodi.fi/`
`https://www.episodi.fi/uutiset/nyt-netflixissa-toimintatahden-paras-leffa-jatko-osa-nousee-toimintafilmien-mestariluokkaan/`
`https://www.como.fi`
`https://www.fum.fi`
`https://www.soundi.fi`
`https://www.inferno.fi`

### What happens?

Ad placeholders on pc and ads on mobile

![image](https://user-images.githubusercontent.com/84513173/126050265-b69d4638-0cec-4f00-ae73-c19413501bb6.png)
![image](https://user-images.githubusercontent.com/84513173/126050294-2ca09ea3-bf41-41ef-b70d-f0c117865952.png) ![image](https://user-images.githubusercontent.com/84513173/126050883-0a2e2cda-7dd5-4ff3-973d-a75407b58de8.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

Might also be happening on other sites that use strossle? I'll try to figure out filters later if still needed.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/7ed66e26e40b80997e53c61d23e3960f43ffd258

**Comment by Nojuuu** [comment]
Ads seem to be still there on mobile.

**Comment by peace2000** [comment]
I'm trying to reproduce but no matter how I try I cannot... Hmm...

Have you updated all your filter lists? Are there any whitelist entries in your logger that could possibly explain this?

**Comment by Nojuuu** [comment]
> 
> I'm trying to reproduce but no matter how I try I cannot... Hmm...
> 

I had to do remote debugging on actual mobile device

**Comment by peace2000** [comment]
Now I got it, I thought it would be an empty placeholder just like that screenshot has. But it was an article that had visible text "mainos". I tried earlier on mobile but had no hits. Maybe I had to scroll to the bottom of the page for the ad to appear.

https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/8e771eaa6af8e0d0da540260a9ea60669977748d

**Comment by Nojuuu** [comment]
![image](https://user-images.githubusercontent.com/84513173/126631109-757bf7ce-41ad-4e4a-8b9c-62d269009bec.png)

On all Disney+ related articles, examples:
`https://www.episodi.fi/uutiset/nyt-disney-plussassa-mukiinmeneva-sotaleffa-ohjaaja-oli-lahella-kuolla-tankin-vuoksi/`
`https://www.episodi.fi/uutiset/nyt-disney-plussassa-legendaarinen-sotaleffa-nappasi-seitseman-oscaria/`
`https://www.episodi.fi/uutiset/arrow-tahti-liittyy-marvel-universumiin-nahdaan-odotetussa-sarjassa/`

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/5ae48835b066121a30199adee43c290df92c4c8f
