### ISSUE TITLE
x2.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#313]
### List the website(s) you're having issues:

`https://x2.fi/`

### What happens?

Ad placeholder

![image](https://user-images.githubusercontent.com/84513173/126143377-9d944f3f-c37f-4623-84ba-974caf11536e.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

`x2.fi##.mobile-top-ad`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/744648eb8178eea364aa3989f0caef3c7c3d7f7c
