### ISSUE TITLE
seura.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#314]
### List the website(s) you're having issues:

`https://seura.fi/ilmiot/tiede-ja-luonto/pepe-forsberg-majava-luottaa-yhteistyon-voimaan/`

### What happens?

EasyList breaks the video player used by this site for their own videos

![image](https://user-images.githubusercontent.com/84513173/126699237-0eb09dbf-48f6-47fc-845f-bfb42e4b473d.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

This unbreaks it:

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=api.screen9.com`

**Comment by peace2000** [comment]
Fix added and pull request for Easylist https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/8c33924ed570dd0f4fdf88096b7622024460a830
