### ISSUE TITLE
suomif1.com, suomifutis.com, suomikiekko.com, valioliiga.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#315]
### List the website(s) you're having issues:

`https://www.suomifutis.com/veikkausliiga/`
`https://www.suomikiekko.com/nhl/`
`https://www.valioliiga.com/ottelukeskus/`
`https://www.suomif1.com/kuljettajat-formula-1/`

### What happens?

Casino ad
![image](https://user-images.githubusercontent.com/84513173/126713913-9d3c2eb6-ae78-44d6-a33e-6503bfb373ac.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

Maybe `#?#[data-bottom-floater]:-abp-contains(LUNASTA TARJOUS!)` or just `##[data-bottom-floater]`?

**Comment by peace2000** [comment]
I think `##[data-bottom-floater]` is fine, those sites are highly ad infested and I doubt they would use that element name for other purposes. https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/428f6cbab19e5ff8c5483828a6a5cf52405cca1f
