### ISSUE TITLE
epari.fi, ilkkapohjalainen.fi, jarviseutu-lehti.fi, jurvansanomat.fi, komiat.fi, suupohjansanomat.fi, vaasanikkuna.fi, viiskunta.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#316]
### List the website(s) you're having issues:

`https://www.epari.fi/`
`https://ilkkapohjalainen.fi/`
`https://www.jarviseutu-lehti.fi/`
`https://www.jurvansanomat.fi/`
`https://www.komiat.fi/`
`https://www.suupohjansanomat.fi/`
`https://www.vaasanikkuna.fi/`
`https://www.viiskunta.fi/`

### What happens?

Ad placeholders
![image](https://user-images.githubusercontent.com/84513173/126895708-a1f57274-6ed0-46db-9a65-a9f71cd0421e.png)
![image](https://user-images.githubusercontent.com/84513173/126895723-e5981198-9f75-47e6-8ad0-0973386fadbe.png)
![image](https://user-images.githubusercontent.com/84513173/126895763-8232a7e4-dea7-438e-b27f-314edfc48db0.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:
```
epari.fi,ilkkapohjalainen.fi,jarviseutu-lehti.fi,jurvansanomat.fi,komiat.fi,suupohjansanomat.fi,vaasanikkuna.fi,viiskunta.fi##.ads__wrapper
```

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/37fbdc05277d595a2effd955d0e60863dd83bd5b
