### ISSUE TITLE
pointti.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#317]
### List the website(s) you're having issues:

`https://pointti.fi/`
`https://pointti.fi/teema/puhelin-on-korvannut-peruskameran/`

### What happens?

Ad placeholder + ad starts/ends text

![image](https://user-images.githubusercontent.com/84513173/126896080-70bb7f88-d2b6-4ad2-80c1-bae3b20b210f.png)

![image](https://user-images.githubusercontent.com/84513173/126896189-1c9a82f7-a0ac-4972-8325-6178664f7d72.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:
```
pointti.fi##.after-ad
pointti.fi##.before-ad
pointti.fi##.paraati
```

There is also a `##.jattiboksi` between the before/after -ad, for the actual ad, but it doesn't take up any space at the moment. However, you can also block it if you want to be sure it never does.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/c5bcf5f4ed8689c3c35234b7bc8900aca10ce6db
