### ISSUE TITLE
cdon.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#318]
### List the website(s) you're having issues:

`https://cdon.fi/kodin-elektroniikka/amd-5800x-suoritin-p68113804`

### What happens?

Ad placeholder

![image](https://user-images.githubusercontent.com/84513173/126896642-63c3d253-889a-40f9-aa18-af8813cf3b47.png)
![image](https://user-images.githubusercontent.com/84513173/126896749-c2ef0164-2936-4598-be22-dfa0e0bcab2d.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

Maybe `cdon.fi##[id^="afscontainer"]` in case that number can change?

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/c5bcf5f4ed8689c3c35234b7bc8900aca10ce6db
