### ISSUE TITLE
audiovideo.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#319]
### List the website(s) you're having issues:

`https://audiovideo.fi/`

### What happens?

Ad

![image](https://user-images.githubusercontent.com/84513173/126978264-c2342c63-4ce3-4b20-bbe2-9fe312ab02b7.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

`audiovideo.fi##[id*="bunyad-widget-ads"]`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/32a99a58ab05f246eb426d2ccd670164bc6fc1f0

**Comment by Nojuuu** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/3ff27289f1c65e01f746eb3d4cee580c76f04825/Finland_adb.txt#L175

Can be removed.

**Comment by peace2000** [comment]
Removed: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/1ccbad8b9522686531477db5d1caf36bdba34345
