### ISSUE TITLE
tiede.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#320]
### List the website(s) you're having issues:

`https://www.tiede.fi/`

### What happens?

Ad + placeholder

![image](https://user-images.githubusercontent.com/84513173/126979277-783ff60d-1db0-40bf-8b7e-a90b7979a9b1.png)
![image](https://user-images.githubusercontent.com/84513173/126980034-63bc3b82-da91-4b62-9177-7aea0f45aade.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

This fixes both:
`tiede.fi#?#.views-row:-abp-has(.is-commercial)`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/3ff27289f1c65e01f746eb3d4cee580c76f04825
