### ISSUE TITLE
fonecta.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#321]
### List the website(s) you're having issues:

`https://www.fonecta.fi/kartat`

### What happens?

Ad placeholder

![image](https://user-images.githubusercontent.com/84513173/127150294-d0b66f88-b62c-4129-9709-85c80336a0f4.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

`fonecta.fi##.map-ad`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/bd324d4679f73d0ebe3758b4250a5d13b010f247

**Comment by Nojuuu** [comment]
![image](https://user-images.githubusercontent.com/84513173/130827517-81bfbaf7-49b5-4aa6-9260-62529f5880ba.png)

`fonecta.fi##[class*=adBox]`

**Comment by peace2000** [comment]
Fixed: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/661630b1e7e4f7339fb2a2964b8950e82711fd23
