### ISSUE TITLE
motonet.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#322]
### List the website(s) you're having issues:

`https://m.motonet.fi/`

### What happens?

EasyList blocks product images on front page.

![image](https://user-images.githubusercontent.com/84513173/128637200-934fb6c2-1251-43b1-b258-b8f09059d435.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 90.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.36.2

### Other details:

`m.motonet.fi#@#.ProductAd`

**Comment by peace2000** [comment]
Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/2cd66760a9d6ff92a47e6f1a79fd14dad53abe0f
