### ISSUE TITLE
kuntalehti.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#323]
### List the website(s) you're having issues:

`https://kuntalehti.fi/`

### What happens?

Ad banner and placeholder

![image](https://user-images.githubusercontent.com/84513173/129565031-8f1347db-2475-44bc-8c89-44fec5cc14df.png)

Ad content
![image](https://user-images.githubusercontent.com/84513173/129565393-74273d1a-99ef-4b61-ab42-1cefde0ded55.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 91.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

`kuntalehti.fi#?#.g:-abp-has(.gofollow)`

`kuntalehti.fi##.ad-container`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/d05804f55fc0e368d54f0e29d593ee68e1503475
