### ISSUE TITLE
golfpiste.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#324]
### List the website(s) you're having issues:

`https://golfpiste.com/`

### What happens?

Ads

![image](https://user-images.githubusercontent.com/84513173/129797047-c265b9d2-f1b3-4b03-b67f-ce8171810d4f.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 91.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

`golfpiste.com##.carousel-cell--native`

Also don't worry about empty spaces it leaves, those should be gone after refresh.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/b19727594b1a499214555ae777658a24ba216e14

There were other ads also here https://golfpiste.com/verkkokauppa/tuote/998_529/koko-lahto/

**Comment by Nojuuu** [comment]
One more:
![image](https://user-images.githubusercontent.com/84513173/129816866-09f10a66-74b7-4e0f-8a9b-11505306d07d.png)
