### ISSUE TITLE
etusuora.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#325]
### List the website(s) you're having issues:

`https://etusuora.com/uutiset/munchen-2022-tulosrajat-julki`

### What happens?

Ad placeholders

![image](https://user-images.githubusercontent.com/84513173/129825601-4eb9ba3d-d952-4c89-b9d2-ecd76abd14dc.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 91.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

`etusuora.com#?#.pb30:-abp-has(.adsbygoogle)`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/1d31aa1f22740bb764337365026768a3367664f6
