### ISSUE TITLE
uusisuomi.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#327]
### List the website(s) you're having issues:

`https://www.uusisuomi.fi/kumppanisisallot`

### What happens?

All articles blocked. Although these are all promotional articles, I think you should still be able to view them via this particular url path.

![image](https://user-images.githubusercontent.com/84513173/129921763-a5dbad14-26f0-4bb7-998e-d026bd681084.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 91.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

I think changing this filter:
`uusisuomi.fi##div:has(:scope > a[href^="https://www.uusisuomi.fi/kumppanisisallot/"])`

to something like this would be better:
`uusisuomi.fi##div:not(.grid-cards__column > .card-post, .site-header__grid, .site-header__navigation > *, .site-header__megamenu > *):has(:scope > a[href^="https://www.uusisuomi.fi/kumppanisisallot/"])`

**Comment by peace2000** [comment]
Actually, when I snooped around `uusisuomi.fi`, I don't see that filter getting any hits in logger. Though in `puheenvuoro.uusisuomi.fi` that filter gets hits. So maybe changing  `uusisuomi.fi##div:has(:scope > a[href^="https://www.uusisuomi.fi/kumppanisisallot/"])` ->  `puheenvuoro.uusisuomi.fi##div:has(:scope > a[href^="https://www.uusisuomi.fi/kumppanisisallot/"])` could be enough?

**Comment by Nojuuu** [comment]
Yeah, we can try that first 👍

**Comment by peace2000** [comment]
Also noticed that filter can be replaced with better filter now: puheenvuoro.uusisuomi.fi##.partner-blog-list

`https://puheenvuoro.uusisuomi.fi/blogiarkisto/`

**Comment by peace2000** [comment]
Will see how it works https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/e99c5c52b647849b02503ee16fa35494af47c468

**Comment by Nojuuu** [comment]
There's one [here](https://vapaavuoro.uusisuomi.fi/) too, I think it can be just `uusisuomi.fi##.partner-blog-list`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/ffdfc858f95da306723d82001c3be4aca38f9e56

I think I want to keep two separate entries as a matter of safety and so that I'll remember for which domains those rules were actually meant for in the first place. Those sites change pretty often.
