### ISSUE TITLE
hattulaan.fi, reska.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#328]
### List the website(s) you're having issues:

`https://hattulaan.fi`
`https://reska.fi/`

### What happens?

A lot of ad banners on both sites

![image](https://user-images.githubusercontent.com/84513173/129937357-e566ee81-9586-4e8c-a6c8-d4daf4d58a02.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 91.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

Maybe:
`hattulaan.fi##[class^="ml-adverts"], .banner`
`reska.fi##[class^="ml-adverts"], .banner:not(:-abp-has([href="https://reska.fi/lounasreska/"]))`

Not sure if that syntax works on ABP.

**Comment by peace2000** [comment]
Did this way: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/ffdfc858f95da306723d82001c3be4aca38f9e56
