### ISSUE TITLE
lily.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#331]
### List the website(s) you're having issues:

`https://www.lily.fi/`

### What happens?

EasyPrivacy breaks element:

![image](https://user-images.githubusercontent.com/84513173/132102561-a67652ca-de40-4309-acf7-75c972f3fe9b.png)

Ad placeholders:

![image](https://user-images.githubusercontent.com/84513173/132102717-2cf5fdc3-4c96-44eb-9a10-97b193a1e331.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 91.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

Need to allow this:
```
@@||fi1.frosmo.com/recoApi/v2?method=multifetch&origin=a_lehdet_fi$xhr,domain=lily.fi
``` 
or if you don't want to allow it:
```
lily.fi##[class^=transitionSlot]:empty
```

________________

For ad placeholders:
```
lily.fi##[class*=ad__component]
```

**Comment by Nojuuu** [comment]
Looks like allowing that also fixes this carousel

![image](https://user-images.githubusercontent.com/84513173/132103998-328d0204-d425-4f31-a47c-3c572180d344.png)

**Comment by peace2000** [comment]
EP issue: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/07d557f0781ee3a88bde634ee54524c7ebb6077f

**Comment by peace2000** [comment]
Ad placeholders: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/7d5f115a7c87d4e5f3f60711912b9267f0ab4ad3
