### ISSUE TITLE
vanha.kaleva.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#332]
### List the website(s) you're having issues:

`https://vanha.kaleva.fi/tapahtumat/haku/daterange=thismonth`
`https://vanha.kaleva.fi/tapahtumat/tapahtuma/asa-band/1039649/`

### What happens?

Ad placeholders:

![image](https://user-images.githubusercontent.com/84513173/132104599-72f45921-76aa-4412-a60e-97baf4c1d9ac.png)

![image](https://user-images.githubusercontent.com/84513173/132104714-2e8a929c-097f-403e-85ed-458efabf6e0b.png)

![image](https://user-images.githubusercontent.com/84513173/132104690-16bad53c-ebbf-4e2c-9f27-65e188896b9a.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 91.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

First pic:
```
vanha.kaleva.fi#?#.box:-abp-has(.list-item-advertisement)
```
__________

For 2nd and 3rd pic maybe:

For uBO only:

```
vanha.kaleva.fi##.event-detail-ad
vanha.kaleva.fi##.col-sm-12.col-md-8.col-lg-9:style(width: 100% !important;)
vanha.kaleva.fi##.event-detail-image:style(background-size: 100% 100% !important;)
```

And for others maybe just for mobile devices, so it doesn't look weird?
```
!#if env_mobile
vanha.kaleva.fi##.event-detail-ad
!#endif
```

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/e5250725269187a636f6d971a986b2a4c3c07dff
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/866d361533a7918b3cb58e2ebca6ca08ccdb854d

Fixed.

It's appalling that ABP still doesn't support style injecting, unlike uBO and Adguard. Will have to wait for that thing to happen... https://gitlab.com/eyeo/adblockplus/abc/adblockpluscore/-/issues/210

I also realized recently that `!#if env_mobile` is not supported by ABP... https://gitlab.com/eyeo/adblockplus/abc/adblockpluscore/-/issues/325 will have to wait for that too, who knows how long. But in this case it won't be an issue as that ad is possible to hide via `vanha.kaleva.fi##.event-detail-ad-mobile` which means that ad is only hidden for mobile devices.
