### ISSUE TITLE
kaaoszine.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#334]
### List the website(s) you're having issues:

`https://kaaoszine.fi/children-of-bodomin-entinen-kitaristi-roope-latvala-chaoszinen-videohaastattelussa-bandista-potkujen-saannin-myota-elamasta-katosi-pohja-mutta-olen-nyt-viime-ajat-kirjoittanut-paljon-uutta-musiikk/`

### What happens?

Ad placeholders:

![image](https://user-images.githubusercontent.com/84513173/132529121-7539e143-834e-4e4e-9fc4-32ffa0590cac.png)
![image](https://user-images.githubusercontent.com/84513173/132529237-990e3da0-0c8b-45d5-91f2-1b787b936243.png)

_________________
Strossle widget blocked by EasyList:

![image](https://user-images.githubusercontent.com/84513173/132532772-252e66d1-5cdf-406f-ac1c-cd0275354f0e.png)

Ad placeholders on strossle widget if whitelisted:

![image](https://user-images.githubusercontent.com/84513173/132533015-92536ee1-8afd-45f0-b76d-c73e6904dd54.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 92.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

First two pics:
```
kaaoszine.fi#?#.rotate:-abp-has(.adten)
kaaoszine.fi###wmg-ad-player
```
______________
Allowing strossle widget:
```
@@||assets.strossle.com/strossle-widget-sdk/1/strossle-widget-sdk.js$script,domain=kaaoszine.fi
@@||widgets.spklw.com/v1/widgets/*$xhr,domain=kaaoszine.fi
@@||images.sprinklecontent.com/500/0/*$image,domain=kaaoszine.fi
```

Placeholders on strossle widget:
```
kaaoszine.fi#?#.col-6.col-sm-3:-abp-has([href*="smartadserver"])
```

**Comment by peace2000** [comment]
Is there a reason why not to use `kaaoszine.fi##.rotate` instead of `kaaoszine.fi#?#.rotate:-abp-has(.adten)` ? Imo "rotate" usually tends to refer ad stuff.

**Comment by Nojuuu** [comment]
Yeah, I think that should be good too. I just saw another #?#.rotate:-abp-has() filter in the logger, so I did it the same way.

**Comment by Nojuuu** [comment]
> I also don't see `kaaoszine.fi#?#.rotate:-abp-has(.adten)` matching anything.

It seems to be random, just noticed that there can also sometimes be `#kaaoszine_desktop-top` etc.

**Comment by peace2000** [comment]
> 
> 
> Yeah, I think that should be good too. I just saw another #?#.rotate:-abp-has() filter in the logger, so I did it the same way.
> 
> https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/2a1e1d08ebba1cd26e2f82633f0c4dbb0e4f082d/Finland_adb.txt#L325

Oh.. I don't understand why I didn't use `kaaoszine.fi##.rotate` earlier. I don't see it causing issues.

Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/2461d611bbb923a32ead4ac69e2e02ab6fccb3a6

**Comment by Nojuuu** [comment]
Looks like there's different ads served on mobile in that strossle widget `kaaoszine.fi##.col-sm-3.col-6:-abp-contains(/mainos/i)`

**Comment by peace2000** [comment]
Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/7f41d28fb554cebffcfa11cbd24545b43a65a7a1

**Comment by peace2000** [comment]
I btw used Android Firefox USB debugging for the first time now... I remember you spoke about it some time ago? It seems useful, though is there any way to open uBO's element picker for phone through PC when using remote debugging?

**Comment by Nojuuu** [comment]
I don't think you can. Rather, it just helps to figure out the class/id or other stuff of the elements when the element picker doesn't provide good options.

I've been just sending the filter to myself and then copypasted it to the element picker to test if it works.

**Comment by peace2000** [comment]
@Nojuuu Well I actually figured out a workaround for this.

Install Teamviewer to your phone and connect to it via your pc. Works actually.

**Comment by Nojuuu** [comment]
I'll test that next time I have to do remote debugging 👍
