### ISSUE TITLE
kaasujalka.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#335]
### List the website(s) you're having issues:

`https://kaasujalka.fi/`

### What happens?

Ad banner:
![image](https://user-images.githubusercontent.com/84513173/132537228-4b1f9fc9-ab6c-4020-85c5-d3d8d443ee63.png)

Ad placeholder: 
![image](https://user-images.githubusercontent.com/84513173/132537401-e5397c0f-bb0a-4044-a554-a640213ee9a2.png)

More placeholders:
![image](https://user-images.githubusercontent.com/84513173/132537738-7769f4f9-9b1f-4e94-b261-c980cb64221a.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 92.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:
```
||kaasujalka.fi/assets/banners/
kaasujalka.fi##[src^="https://kaasujalka.fi/assets/banners"]
kaasujalka.fi###header_container
kaasujalka.fi#?#.widget-container:-abp-has([class^=ad_])
```

**Comment by peace2000** [comment]
For some reason I missed this report yesterday. Well, fixed now anyway: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/7ee5bef9acbaec24318e04e95f95a8984c3783d8
