### ISSUE TITLE
suomimobiili.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#337]
### List the website(s) you're having issues:

`https://suomimobiili.fi/hyvin-edullisen-googlen-ja-jion-kehittaman-4g-alypuhelimen-julkaisu-viivastyy-syyna-piiripula-ja-testaus/`

### What happens?

Ad:
![image](https://user-images.githubusercontent.com/84513173/132881853-5db71224-554a-42ed-aa96-5e51b403ff6e.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 92.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:
```
suomimobiili.fi#?#p:-abp-contains(MAINOS)
```

**Comment by peace2000** [comment]
Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/1d92850b27070187d9cc590fa77d0b126e51ac41
