### ISSUE TITLE
voice.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#339]
### List the website(s) you're having issues:

`https://www.voice.fi/`

### What happens?

Ad/Sponsored articles:
![image](https://user-images.githubusercontent.com/84513173/133803821-c4f20ebc-2590-4b8a-ad2e-bc6200198863.png)
![image](https://user-images.githubusercontent.com/84513173/133803744-901091e9-c8ca-496a-b30d-15120beca0cf.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 92.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:
```
voice.fi#?#div.item:-abp-has(.sponsored)
voice.fi##.article-sponsored
```

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/413890064a1298e32cae02f3adaa4c91138a0147

Btw, Easylist Cookie is included in Fanboy's Annoyance, so ELC doesn't need to selected separately.

**Comment by Nojuuu** [comment]
That's a pretty old picture, I'll update it the next time I post new issue. I haven't used Fanboy's Annoyance for a while.
