### ISSUE TITLE
iltalehti.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#340]
### List the website(s) you're having issues:

`https://www.iltalehti.fi/iltv-paivarinta/a/efc6d8b4-0806-4696-a6b3-1b652c7d9964`

### What happens?

Adblock nag and videos won't play. The problem is caused by EasyList.

![image](https://user-images.githubusercontent.com/84513173/134036403-bb08eba2-f465-4fd6-887a-d080c83b1281.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 92.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:
~~`@@||ssl.p.jwpcdn.com/player/plugins/vast/v/*/vast.js$script,domain=iltalehti.fi`~~

E: nvm, I still sometimes get that nag and sometimes not when I clear the cache, so I guess the problem is somewhere else?

**Comment by Nojuuu** [comment]
Umm, if I disable EasyList I can't reproduce that nag, but when I enable it and check the logger, I don't see it blocking anything related other than that what I already tried to suggest?

**Comment by Nojuuu** [comment]
Even if I whitelist everything related to that video player, I still get that nag...

Only thing that has helped so far is `@@||iltalehti.fi^$generichide`

**Comment by peace2000** [comment]
Does `iltalehti.fi#@#.ad-placement` help?

**Comment by Nojuuu** [comment]
Yeah, I think it's that one.

**Comment by peace2000** [comment]
Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/22fa9447444d6f84330b4b432c248c05a0c6f0e2

**Comment by peace2000** [comment]
Btw, @Nojuuu you can ignore the official issue report form and report more freely, in order to decrease burocracy as you file these reports often. As long as the report is clear, it's fine.

**Comment by peace2000** [comment]
> 
> 
> Btw, Nojuuu you can ignore the official issue report form and report more freely, in order to decrease burocracy as you file these reports often. As long as the report is clear and understable, it's fine.

@DandelionSprout you are allowed to follow the principle here as well.
