### ISSUE TITLE
gamereactor.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#341]
### List the website(s) you're having issues:

`https://www.gamereactor.fi/league/`

### What happens?

Ad placeholder

![image](https://user-images.githubusercontent.com/84513173/134412105-b32e5c8f-ae1d-4f6d-ba4e-b7a61f793752.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 92.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

```
gamereactor.fi##.ad_video
```

**Comment by peace2000** [comment]
Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/88470671ffe3e9b9588fd031c5b8edb0c8cc3735
