### ISSUE TITLE
mikrobitti.fi / mediuutiset.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#342]
### List the website(s) you're having issues:

`https://www.mikrobitti.fi/`
`https://www.mikrobitti.fi/uutiset/microsoft-julkisti-uutuuksia-puhelin-lappari-ja-hybridilaitteita/8c71dff7-7505-4ac7-b2e1-8951f2b236d3`

### What happens?

Similar issues as yesterday with `kauppalehti.fi` when window width is smaller

Stuff hidden on frontpage:
![image](https://user-images.githubusercontent.com/84513173/134774982-be68f11e-cf13-498b-8895-1273ac155e4f.png)

Ad placeholder:
![image](https://user-images.githubusercontent.com/84513173/134774889-9fa1775b-1380-48dc-95dc-a88e15a8833e.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 92.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

Filter that causes issues:
`mikrobitti.fi#?#div[class]:-abp-has(> div[width] > .ad:not(aside)))`

Haven't had time to figure out any filter suggestions yet.

**Comment by peace2000** [comment]
Removed it https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/56e44c4a34580b8952e27c55cb06ea1bccba4024 let's see...

**Comment by Nojuuu** [comment]
`mikrobitti.fi##div[class][width]:-abp-has(.ad)` works for placeholder but top one needs something for the parent div.

**Comment by peace2000** [comment]
Imo these two will handle it correctly:

`mikrobitti.fi#?#div[class]:-abp-has(> [width] > [id|="almad"]:not([id|="almad-mobileParade"]))`
`mikrobitti.fi#?#div[class][width]:-abp-has([id|="almad-mobileParade"])`

**Comment by Nojuuu** [comment]
Seems to work 👍 

Btw, I just noticed theres also issues on `https://www.mediuutiset.fi/` and I would also keep an eye out for other alma media sites making similar changes that break filters. They seem to usually slowly roll out somewhat similar changes to some of their sites

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/3a7787c42a2f03c4dcd401e8828d240464afef54

**Comment by peace2000** [comment]
Yeah they seem to do that. What issues there are on mediuutiset.fi? Only that placeholder at the top or some others as well?

**Comment by Nojuuu** [comment]
I think it's just that, at least for now.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/e92e20c2c15f8aadeb0b1df9ee9314091253c029

**Comment by peace2000** [comment]
Added a small safety measure to not block if it matches to mobile ad. I'll keep this open for a while.

**Comment by peace2000** [comment]
mediuutiset.fi looks ok to me.

**Comment by Nojuuu** [comment]
@peace2000 

uusisuomi.fi

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/a84d7e0fb19940458fe1b456b3efbeadbb6a1a69

**Comment by Nojuuu** [comment]
@peace2000 

https://www.tekniikkatalous.fi/tyopaikat/kumppanisisalto-tyopaikat/625c7c24-bd5c-4a00-8d65-edac2d29438f

**Comment by peace2000** [comment]
Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/3d0906111cc3ea8cef7382306acdf05bc764da7d

**Comment by Nojuuu** [comment]
@peace2000 

Today list of all news is now hidden:
https://www.tekniikkatalous.fi/uutiset

**Comment by peace2000** [comment]
Nasty issue. Removed problematic rules https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/0df7085d37e8d7dc6707e61f316cfdda2377e23f

**Comment by peace2000** [comment]
Will have to check new rules soon if needed.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/e6dacf921792d5dcfd9a9fc5e813d0ce3da78ce7 tivi

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/37f1ddf3577aee8db1381853fcf9370ed4e9c0ee tekniikkatalous

These new rules are unlikely to backfire when they next time decide to change something.
