### ISSUE TITLE
lily.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#343]
### List the website(s) you're having issues:

`https://www.lily.fi/`

### What happens?

Huge ad placeholder:
![image](https://user-images.githubusercontent.com/84513173/134777223-29b48ebe-039e-4849-86f1-b8443c3a005b.png)

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 92.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

</details>

### Other details:
```
lily.fi##[class^=pageFeed__topAdSlot]
```

**Comment by Nojuuu** [comment]
Another one:
![image](https://user-images.githubusercontent.com/84513173/134777678-a37fa224-75b3-47f5-bd6d-2d88b77345f9.png)

**Comment by peace2000** [comment]
Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/25b7a905657918c13107dd0ef9eb9f0a277ed374

Ad containers of that size (sample #1) should be illegal.
