### ISSUE TITLE
pirkkalainen.com

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#344]
Ads https://www.pirkkalainen.com/

**Comment by Nojuuu** [comment]
```
pirkkalainen.com##.custom:has(:not([href*="www.pirkkalainen.com"]) > [src*="/images/mainospaikat/"])
```

**Comment by peace2000** [comment]
After thinking this a while, I think that only that Citymarket banner https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/60cc8bd3036dd97846f55770727e072af9dc3b64 should be blocked as it's actually only "ad". I consider those others as annoyances. They are not selling anything.

Btw, they don't often change those elements: https://web.archive.org/web/20190328043510/https://www.pirkkalainen.com/ - looked pretty similar in 2019 so I think it's safe to use these rules I added.
