### ISSUE TITLE
forssanlehti.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#346]
Fix title not loading https://www.forssanlehti.fi/

**Comment by Nojuuu** [comment]
If you mean that big site title at the top, it loads fine for me

**Comment by peace2000** [comment]
Yeah. It was caused by Fanboy's Social blocking list. Added a fix and also blocked ads. https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/f77388931aa48743cb1ecc4910288943771413db
