### ISSUE TITLE
kiuruvesilehti.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#347]
Fix blocked scrolling https://kiuruvesilehti.fi/

**Comment by peace2000** [comment]
Fixed anti user behavior and also blocked that big self promition banner https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/55df63ed32110281b7d9c6c6f8a3500647125021

Typically self-promotion is not blocked but I think that I block it if it's annoying enough.

**Comment by Nojuuu** [comment]
> Typically self-promotion is not blocked but I think that I block it if it's annoying enough.

Yeah, I don't think that's an issue here since they have other links to order their magazine.
