### ISSUE TITLE
ylasatakunta.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#350]
Ads: https://www.ylasatakunta.fi/

**Comment by Nojuuu** [comment]
``` 
ylasatakunta.fi##.ad
ylasatakunta.fi#?#.ank-col-item:-abp-contains(Kaupalliset tiedotteet)
ylasatakunta.fi##[href*="/artikkeli-kaupallinen-"]
```

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/239a0a6202676494650e52ee246054269bb041f4

Had to do things in a little bit complex manner in order not to block non ads.
