### ISSUE TITLE
sss.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#354]
Ads: https://www.sss.fi/

**Comment by Nojuuu** [comment]
```
sss.fi#?#.td_block_wrap:-abp-has([href="https://www.sss.fi/category/mainos/"])
```

**Comment by peace2000** [comment]
Thanks, fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/4d543462bedf7b37372417b7b8648d63d91b4126

Last night I went through dozens of news websites and didn't have time to fix all of them one by one so I added them here as a "to-do" list.
