### ISSUE TITLE
hameensanomat.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#355]
Ads: https://www.hameensanomat.fi/

**Comment by Nojuuu** [comment]
```
hameensanomat.fi#?#.herald_posts_widget:-abp-contains(Kaupallinen yhteistyö)
```

Maybe?

**Comment by peace2000** [comment]
I didn't get any hits with that rule for some reason.

https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/497a949a5c4b6813a1184e2370e4d57f4c27aa1c

**Comment by Nojuuu** [comment]
It was there when I checked it but can't find it atm either.

But there's also this one:
![image](https://user-images.githubusercontent.com/84513173/135566189-e57a11ef-06d2-48d7-ada5-a1365ce303a1.png)

**Comment by peace2000** [comment]
That's the element I targeted with `#?#.herald-sidebar > .herald_posts_widget:-abp-has(a[href^="https://www.hameensanomat.fi/kaupallinen-yhteistyo/"])` have you updated your lists?

![kuva](https://user-images.githubusercontent.com/17256841/135578052-3a0d8012-bbcb-4508-bc78-70f5e55e0eb2.png)

**Comment by Nojuuu** [comment]
> have you updated your lists?

Apparently not, my bad...

**Comment by peace2000** [comment]
I was already afraid this page would use diffrent DOM structures for different IP's... :D that's something Facebook does for users in different coutries. Though it's very unlikely that a small local newspaper would take that extreme measures.
