### ISSUE TITLE
ksml.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#358]
### List the website(s) you're having issues:

`https://www.ksml.fi/urheilu/4313898`

### What happens?

Ads on mobile:
<img src="https://user-images.githubusercontent.com/84513173/135513896-01b1c1dc-265e-4adb-8029-cd6dabaf1de2.png" width="49%"><img src="https://user-images.githubusercontent.com/84513173/135513878-b055158b-b0f4-4cc7-9c1d-902f59eb5aec.png" width="49%">

And placeholders:
<img src="https://user-images.githubusercontent.com/84513173/135516143-bf8054cd-d957-4766-8353-e1724b5bb5f7.png" width="49%">

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 92.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

</details>

### Other details:
```
ksml.fi##.card--native
ksml.fi##.display-ad
```

**Comment by Nojuuu** [comment]
aamuposti.fi too, and probably other similar sites?

![Screenshot_20211001-114238](https://user-images.githubusercontent.com/84513173/135591563-e354ee31-38b3-42d9-bf5a-cd47e2b292d8.jpg)

![Screenshot_20211001-114135](https://user-images.githubusercontent.com/84513173/135591675-4b374997-8f93-4918-a35e-b7889f4ae6a4.jpg)

**Comment by peace2000** [comment]
This list already has this entry:

`##.card--native`

hmm...

**Comment by Nojuuu** [comment]
Do you see these on mobile?

**Comment by peace2000** [comment]
Nope, tested in a real mobile phone.

In logger, is `##.card--native` being appliead for you at all? Or `##.display-ad` ?

And you don't have cosmetic rules disabled?

**Comment by peace2000** [comment]
If you refresh the page a couple of times do you still see those or do they disappear?

**Comment by Nojuuu** [comment]
> And you don't have cosmetic rules disabled?

I did... 😄  I want to remove that setting completely, I literally never use it and it always turns on somehow.... No wonder I also saw cookie dialogs everywhere yesterday.

**Comment by peace2000** [comment]
It's useful feature for testing but yeah I also sometimes forget to turn it off too.. 😅

Btw, do you sometimes see supposed-to-be-hidden elements blinking once before they are hid? Even if they are targeted via non-procedural cosmetic rule?

**Comment by peace2000** [comment]
That happens usually beucase they are being hid via generic cosmetic filter. Specific filters don't blink.

I recommend reading this conversation: https://github.com/easylist/easylist/pull/9270

**Comment by peace2000** [comment]
If you see in Finnish sites any ads that blink due to being hid via a generic filter, you can report them here and I'll add a specific filter for them.
