### ISSUE TITLE
kansanuutiset.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#359]
### List the website(s) you're having issues:

`https://www.kansanuutiset.fi/`

### What happens?

Leftover text and space from ads:

![image](https://user-images.githubusercontent.com/84513173/136694847-92bf8b7d-9ce7-48fe-af38-d3c7f8c57bbd.png)

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 92.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

</details>

### Other details:

```
kansanuutiset.fi#?#.cb-module-block.cb-box.cb-a-large.clearfix:-abp-has([id|=div-gpt-ad])
```

Maybe? Although it seems to flash quickly before it disappears.

**Comment by peace2000** [comment]
Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/e49dda938b94c6d4110b32819773b9a7f258faf1

For some reason I don't see flashes of it even after refreshing the page mane times, bypassing cache.

Also possible to use a html filter for Firefox https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/2983f2c09aa47bf6db989e3b9205c949cd5adddc - this one can't flash.

**Comment by peace2000** [comment]
PC's hardware can affect as well how well those work. Though it's site specific also.

Also other addons and rules could interfere.
