### ISSUE TITLE
muropaketti.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#364]
### List the website(s) you're having issues:

`https://muropaketti.com/`

### What happens?

![image](https://user-images.githubusercontent.com/84513173/139419817-17039501-06a8-41fe-8058-a9b588476c60.png)
![image](https://user-images.githubusercontent.com/84513173/139419853-dac73624-4511-43d0-9b2b-754b2f2e5878.png)

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 93.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:
```
muropaketti.com##.widget_ads_carousel
```

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/acab5d9ab3a9dd0eb197901954ecb28e123e5d45
