### ISSUE TITLE
terve.fi, meillakotona.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#365]
### List the website(s) you're having issues:

`https://www.terve.fi`

### What happens?

Huge ad placeholders.

![image](https://user-images.githubusercontent.com/84513173/139422271-ec13f6aa-4216-46a1-adfb-7a692ee1df3f.png)

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 93.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:
```
terve.fi##[class*=ad__component]
```

**Comment by peace2000** [comment]
Fixed
