### ISSUE TITLE
tehylehti.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#366]
### List the website(s) you're having issues:

`https://www.tehylehti.fi/fi`

### What happens?

Ads

![image](https://user-images.githubusercontent.com/84513173/139541488-636d6d4b-5975-4698-9f9a-2b00b08c78ff.png)

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 93.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:
```
tehylehti.fi##.magazine-feed > .views-row > .node-promoted
```

**Comment by Nojuuu** [comment]
Seems like just `tehylehti.fi##.node-promotion` works too.

**Comment by peace2000** [comment]
The looks safe to me: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/4a38553c22a0234aa43367bab52e5b78581dbadb
