### ISSUE TITLE
ts.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#368]
### List the website(s) you're having issues:

`https://www.ts.fi/uutiset/paikalliset/5467900/Riskihylky+Beatrisin+saneerausoperaatio+Saaristomerella+on+paattynyttankeista+ei+loytynytkaan+oljya`

### What happens?

![image](https://user-images.githubusercontent.com/84513173/139841968-e14fbaa1-a034-4068-800d-d0175d7c089f.png)

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 93.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:
```
ts.fi#?#.tsv3-c-common-twocolumnslayout:-abp-contains(Lue myös nämä yhteistyö­kumppanimme artikkelit)
```

There's soft hyphen between the words yhteistyö and kumppani, I'm not sure if it causes any problems.
![image](https://user-images.githubusercontent.com/84513173/139842850-41d55c25-e9ce-4813-ab38-172973889a29.png)

**Comment by peace2000** [comment]
Eventually did it this way: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/5e3b46889dcb3ec9fb215e2359835f7ef6fe3ce0

I'm having a busy week but I'll check other issue reports when I have time.
