### ISSUE TITLE
tilt.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#370]
### List the website(s) you're having issues:

`https://www.tilt.fi/uutiset/rip-ar-harry-potter-olit-liian-kaunis-tahan-maailmaan/`

### What happens?

Ad placeholders:
![image](https://user-images.githubusercontent.com/84513173/140236654-50b62f26-8c08-4fce-8ed5-26b33cdd213b.png)

![image](https://user-images.githubusercontent.com/84513173/140237602-286b92db-597e-4ed1-9399-08969d0c58c3.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 93.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:
```
tilt.fi#?#div[style="min-height:552px;"]:-abp-has([id^="tilt_smart_paraati"])
tilt.fi#?#div[class="w-full bg-white border-gray-200 border-b py-2 px-4"]:-abp-has([id^="tilt_smart_boksi"])
```

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/1eb79308b899f12cffc1d3069ff56de4e6c35fc7

**Comment by Nojuuu** [comment]
@peace2000 

Same issue on como.fi

```
como.fi,tilt.fi#?#[style^="min-height:"]:-abp-has([id*="_smart_paraati_"])
como.fi,tilt.fi#?#[class="w-full bg-white border-gray-200 border-b py-2 px-4"]:-abp-has([id*="_smart_boksi_"])
```
