### ISSUE TITLE
huuto.net Hintaseuranta ad

### ISSUE THREAD

**Issue by 07416** [finnish-easylist-addition/finnish-easylist-addition#371]
### List the website(s) you're having issues:

`https://www.huuto.net/osasto/tietotekniikka/komponentit-ja-oheislaitteet/naytot/59`

### What happens?

screenshot of the element `###hise-items-container`:

![image](https://user-images.githubusercontent.com/14923168/140384608-35dc0c9c-0426-4c8b-b841-a03a85b3a66e.png)

**Comment by peace2000** [comment]
Thanks, fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/7d5ad2521e675606150392243ccc8ee4107e9faf

Sorry for long reply time, have been busy for the last couple of weeks.
