### ISSUE TITLE
iltalehti.fi/telkku

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#374]
### List the website(s) you're having issues:
`https://www.iltalehti.fi/telkku/`

### What happens?

Ad placeholders:

![image](https://user-images.githubusercontent.com/84513173/141700264-7bc06f10-d3a3-46c9-af9e-3a3fe535a8d7.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:
```
iltalehti.fi##.telkku-ads
```

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/784c22cc6b58ed883ad06d2902f0eaa3a3e38da9

**Comment by Nojuuu** [comment]
@peace2000 

![](https://user-images.githubusercontent.com/84513173/141990595-cbfca083-3169-4c67-988e-a7902e382b6e.jpg)


`https://www.iltalehti.fi/telkku/ohjelmat/seitseman-uutiset/3165/mtv3/11756846`

**Comment by peace2000** [comment]
Fixed too: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/c0890bc2ab3c6f033fb07d626eac6d632f556ca7
