### ISSUE TITLE
kauppalehti.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#375]
### List the website(s) you're having issues:
`https://www.kauppalehti.fi/uutiset`

### What happens?

Breakage when window width is small/on mobile:
![image](https://user-images.githubusercontent.com/84513173/141995488-b63f2c10-7100-4073-9cbb-9f0fab6fd3f5.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:

Filter that causes this issue:

https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/784c22cc6b58ed883ad06d2902f0eaa3a3e38da9/Finland_adb.txt#L377

**Comment by Nojuuu** [comment]
These are also back on the front page when the window width is small or on mobile devices:

![image](https://user-images.githubusercontent.com/84513173/141997374-e1537cd3-f74d-4ed5-b5ee-15a34181c301.png)


```
kauppalehti.fi##a[class][href^="https://www.kauppalehti.fi/kumppanisisallot/"][target="_self"][rel="noopener"]
```

**Comment by peace2000** [comment]
Removed the problematic https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/86038f9cd72e5389b230c7394e13dc9517b8db1e let's see what would be better..

**Comment by peace2000** [comment]
Ok removing it didn't reveal any ads (at least what I saw), added suggested filter: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/be96e69e46d0a01e212502be82cba189d3c645f2
