### ISSUE TITLE
arvopaperi.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#376]
### List the website(s) you're having issues:
`https://www.arvopaperi.fi/porssi/`

### What happens?

Ad placeholder:
![image](https://user-images.githubusercontent.com/84513173/142002770-86e7673d-18cc-4ec9-8c78-b46c13215711.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:

```
arvopaperi.fi##.ads-parade-wrapper
```

**Comment by Nojuuu** [comment]
![image](https://user-images.githubusercontent.com/84513173/142004276-5faabb35-42d7-428e-a2a8-7ccdebc27fb4.png)

```
arvopaperi.fi##a[href^="https://www.arvopaperi.fi/kumppanisisallot/"][target="_self"]
```

or 

```
arvopaperi.fi,kauppalehti.fi##a[href*="/kumppanisisallot/"][target="_self"]
```

**Comment by Nojuuu** [comment]
If they keep changing those, you can also try something like this for uBO `##:not(:matches-path(/kumppanisisallot/)) [href*="/kumppanisisallot/"]`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/dd19551bcde4392daa2740d6b4db2c7146e37ed8
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/c6aa7e480830a2f8db81c4cab30537cfa1c93e57

Thanks, added.

**Comment by peace2000** [comment]
`kauppalehti.fi##a[href*="/kumppanisisallot/"][target="_self"]` would remove:

![kuva](https://user-images.githubusercontent.com/17256841/142033781-e038d1aa-2010-4768-8fb4-cf1eb8b9cba9.png)

**Comment by Nojuuu** [comment]
Hmm, other sites seemed to have it without `/` at the end.

**Comment by Nojuuu** [comment]
I am going to try this at least for my own filters:

```
arvopaperi.fi,kauppalehti.fi,mikrobitti.fi,talouselama.fi,tekniikkatalous.fi,tivi.fi,uusisuomi.fi##:not(:matches-path(/kumppanisisallot/)) [href*="/kumppanisisallot/"]:not(nav > ul > li > a)
```
