### ISSUE TITLE
tinderinparhaat.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#377]
### List the website(s) you're having issues:
`https://www.tinderinparhaat.com/`

### What happens?

Ad placeholder:
![image](https://user-images.githubusercontent.com/84513173/142617527-4d010c61-a0ea-4c39-a80f-54b785a16c35.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:

```
tinderinparhaat.com##.adf-placement-top
```

**Comment by Nojuuu** [comment]
Not related to this issue but do you notice any problems on these sites:
`https://www.aamulehti.fi/`
`https://www.satakunnankansa.fi/`
`https://www.hs.fi/`
`https://www.jamsanseutu.fi/`
`https://www.kmvlehti.fi/`
`https://www.nokianuutiset.fi/`
`https://www.valkeakoskensanomat.fi/`
`https://www.tyrvaansanomat.fi/`
`https://www.suurkeuruu.fi/`
`https://www.rannikkoseutu.fi/`
`https://www.janakkalansanomat.fi/`
`https://www.kankaanpaanseutu.fi/`
`https://www.merikarvialehti.fi/`
`https://www.sydansatakunta.fi/`

if you block `||er.sanoma-sndp.fi/stats/`? It should probably be added to EasyPrivacy if there are no problems.

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/0e07b48b9369e8f092576bf5bf220031c0da48ef

Didn't see any issues with that stats-server: https://github.com/easylist/easylist/pull/9793
