### ISSUE TITLE
Alma Media ad placeholders

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#378]
### List the website(s) you're having issues:

```
arvopaperi.fi
kauppalehti.fi
mediuutiset.fi
mikrobitti.fi
talouselama.fi
tekniikkatalous.fi
tivi.fi
uusisuomi.fi
```

### What happens?

Ad placeholders still there with some blockers that do not support `:-abp-has()` or `:-abp-contains()`, such as Vivaldi's or Brave's built-in blockers.

<img src="https://user-images.githubusercontent.com/84513173/142728104-819799ee-9b58-47e6-bdf4-28aebd2ec676.jpg" width="49%"> <img src="https://user-images.githubusercontent.com/84513173/142728157-2f758dd6-6b66-48e4-ba83-69be40962f27.jpg" width="49%">

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:

I noticed that it might be possible to get rid of them with just `[class^="p2m385-"]`, as it seems to have been used with these elements for some time:

![image](https://user-images.githubusercontent.com/84513173/142727608-d602af29-c5ad-42ff-957c-a8b712b3b9f9.png)

```
arvopaperi.fi,kauppalehti.fi,mediuutiset.fi,mikrobitti.fi,talouselama.fi,tekniikkatalous.fi,tivi.fi,uusisuomi.fi##[class^="p2m385-"]
```

**Comment by peace2000** [comment]
That's a bad call not to support them. uBO, AG and Easylist do support.

Does Vivalvi / Brave support uBO's `has` or `has-text` syntax?

**Comment by Nojuuu** [comment]
Doesn't look like it. However, I noticed that Brave seems to at least support `:style()`.

**Comment by peace2000** [comment]
@ryanbr as you are affiliated with Brave, can you comment why it doesn't support `:-abp-has()`, `:-abp-contains()`, `has()` and `has-text()` ?

**Comment by Nojuuu** [comment]
It looks like that it has been soon™ since 2019, unless they have cancelled it completely.

https://github.com/brave-experiments/ad-block/issues/228#issuecomment-562769281

**Comment by Nojuuu** [comment]
It seems to be a low priority:
https://github.com/brave/adblock-rust/issues/59

**Comment by ryanbr** [comment]
Also https://github.com/brave/adblock-rust/issues/145 (and other procedural filters)

**Comment by antonok-edm** [comment]
@peace2000 We haven't gotten around to it yet because procedural filters are a bit more complicated to implement than ordinary cosmetic filters - but it's definitely planned/desired.

**Comment by peace2000** [comment]
Hi, ok thanks for the info!

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/d004136ad6927cb0998d8f4d5a8b6c600ef91e16
