### ISSUE TITLE
hyvaterveys.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#379]
### List the website(s) you're having issues:

`https://www.hyvaterveys.fi/`

### What happens?

Ads
![image](https://user-images.githubusercontent.com/84513173/142728815-21c483eb-5fd9-40e1-835b-9871b14cd096.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:

```
hyvaterveys.fi#?#.views-row:-abp-has(.is-commercial)
```

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/a85903fe8661162f579301b9b1f4be0d0264c3cc
