### ISSUE TITLE
seiska.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#380]
### List the website(s) you're having issues:

`https://www.seiska.fi/`

### What happens?

Ads
![image](https://user-images.githubusercontent.com/84513173/142731024-bb6227f7-2f0a-4949-941e-61d80d52b088.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:

Maybe:
```
seiska.fi##.dre-item--skin-native
```

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/7448a9db836ed17f8f120dd0fb11eeb8433177d9
