### ISSUE TITLE
soundi.fi promotional posts

### ISSUE THREAD

**Issue by 07416** [finnish-easylist-addition/finnish-easylist-addition#381]
### List the website(s) you're having issues:

`https://www.soundi.fi/advertoriaali/`

### What happens?

Promotional posts ("ilmoitus") which also appear in the main feed (the website frontpage).

I propose the filter `soundi.fi##.status-publish.type-advertoriaali`

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/d52115563ce86b785f3802cd348bdb82ecb75a51 (also checked sister sites).

Added filters to hide those posts when they are not under `/advertoriaali/` page as it's a dedicated page for ads and access to ads should not be blocked in case someone wants to view them by opening their dedicated page - only ads that appear in other pages should be blocked.
