### ISSUE TITLE
kuntsari.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#383]
### List the website(s) you're having issues:

```
https://www.kuntsari.fi/
```

### What happens?

Ad.

![image](https://user-images.githubusercontent.com/84513173/143075165-30964b1f-deae-4d80-89aa-7f24f49357cc.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:

Maybe  something like:
```
kuntsari.fi##[auto-grid-data*="mainos"]
```

**Comment by peace2000** [comment]
Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/43d5a1f3bae4b140ecef7df436c568b2fd3a05f9 targeted parent element to avoid annoying white space.
