### ISSUE TITLE
tekniikanmaailma.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#384]
### List the website(s) you're having issues:

```
https://tekniikanmaailma.fi/amazonin-digitaalinen-ilmoitustaulu-tulee-myyntiin-silla-on-silmat-korvat-ja-se-tunnistaa-katselijansa/
```

### What happens?

Ad.

![image](https://user-images.githubusercontent.com/84513173/143522938-5762d223-acf7-482c-a128-023bc5514805.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:
```
||kotiliesi.fi/upotukset/hintaopas/*$domain=tekniikanmaailma.fi
```

**Comment by peace2000** [comment]
Added: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/eb9b36c50eb6dea70466a0b31c86af2d27fd0f28
