### ISSUE TITLE
kotiliesi.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#385]
### List the website(s) you're having issues:

```
https://kotiliesi.fi/
```

### What happens?

Ads.

![image](https://user-images.githubusercontent.com/84513173/143690082-fc36f559-7924-4a7b-a5eb-14bfdb81eff8.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:
```
kotiliesi.fi#?#article[class^="grid__item_"]:-abp-has(.template-item_nativead)
```

**Comment by peace2000** [comment]
Thans, added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/d1db4232a316f6866a73210d353d823fa65a2f0c
