### ISSUE TITLE
como.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#386]
### List the website(s) you're having issues:

```
https://www.como.fi/uutiset/harva-tietaa-etta-macgyver-eli-richard-dean-anderson-oli-mukana-kulttipelissa-vuonna-1997/
```

### What happens?

Ad placeholders:

![image](https://user-images.githubusercontent.com/84513173/144504958-6db14bd4-f7f3-4415-baa1-6c81a2e02480.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:
Maybe change these:
https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/f092ae1abbf460e53180b54e575aa0a3cea31dc5/Finland_adb.txt#L718-L719
to:
```
como.fi,tilt.fi#?#div[class="w-full bg-white border-gray-200 border-b py-2 px-4"]:-abp-has([id*="_smart_boksi"])
como.fi,tilt.fi#?#div[style^="min-height:"]:-abp-has([id*="_smart_paraati"])
```

**Comment by peace2000** [comment]
Added: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/a2c28d01618dacaf914ed91281e8c23344551ce3
