### ISSUE TITLE
iltalehti.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#388]
### List the website(s) you're having issues:

```
https://www.iltalehti.fi/
```

### What happens?

Ad articles seem to be back:
![image](https://user-images.githubusercontent.com/84513173/146130351-676c11e5-edbd-4b1c-abf9-244b75c591d2.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 94.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.38.6

</details>

### Other details:

```
iltalehti.fi#?#.card.fp-container:-abp-has([src*="KAUPALLINEN%20YHTEISTY"])
```

**Comment by peace2000** [comment]
I fixed it yesterday: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/88fcbe075702556501f4146e69085e2b9aad6265, does this work for you?

**Comment by Nojuuu** [comment]
Oh, my bad...
