### ISSUE TITLE
laliiga.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#389]
### List the website(s) you're having issues:

```
https://www.laliiga.com/2021/12/17/md-diego-costa-saattaa-palata-la-ligaan/
```

### What happens?

Ad:
<img src="https://user-images.githubusercontent.com/84513173/146632564-ff41cd08-6cdb-4b7a-8408-28d06302c9fd.jpg" width="60%">

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 95.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.39.2

</details>

### Other details:

```
laliiga.com##.pnad-container
```

**Comment by Nojuuu** [comment]
Same issue on viikonloppu.com, sketsi.net and nainen.com

**Comment by peace2000** [comment]
Thanks, fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/bc6d9c9854788d58beaf1449edef518d6aa3ceb3
