### ISSUE TITLE
uusiteknologia.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#390]
### List the website(s) you're having issues:

```
https://www.uusiteknologia.fi/2021/12/23/uuden-ajan-supersuorittimet-armv9-ja-muu-kisaajat/
```

### What happens?

Ad banners:
![image](https://user-images.githubusercontent.com/84513173/147209692-061dce89-3ab8-4e87-936b-4c4824181018.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 95.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.39.2

</details>

**Comment by peace2000** [comment]
`uusiteknologia.fi##.widget_block`

This seems to be fine, it targets ads and a couple of empty containers but doesn't target any non-ad elements.

**Comment by Nojuuu** [comment]
Looks like it might be fine. I wasn't sure what would be a good filter so I didn't suggest any.

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/67ea0cb9ce226946724038e6b3d95dd33edbc95e
