### ISSUE TITLE
seiska.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#391]
### List the website(s) you're having issues:

```
https://www.seiska.fi/
```

### What happens?

Ad placeholder:
![image](https://user-images.githubusercontent.com/84513173/147647625-b53e1df4-1b18-4231-9a5c-ed87d1977f15.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 95.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.39.2

</details>

### Other details:
```
seiska.fi#?#article:-abp-has(a[href=""][rel="no-index,no-follow"])
```

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/9f5f87b8f06c5f36e8f76aa464186ee2959b55e2
