### ISSUE TITLE
voima.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#392]
### List the website(s) you're having issues:

```
https://voima.fi/
```

### What happens?

Ad banner:
![image](https://user-images.githubusercontent.com/84513173/147683023-c71933e1-cdff-45d8-b55c-9b02d3bca39b.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 95.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.40.2

</details>

### Other details:

```
voima.fi##.voima-banneri-etusivulla
```

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/6a77f55d05d96179f753b24cd41a4a9b975733a4

**Comment by Nojuuu** [comment]
@peace2000 

![Screenshot_20220121-192400](https://user-images.githubusercontent.com/84513173/150572209-20765143-b5bf-4fb4-bca2-9c7c88d0b073.jpg)

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/aee8b291d26f211e4b717e4ff9e6b7add687be13 added
