### ISSUE TITLE
pelikone.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#394]
### List the website(s) you're having issues:

```
https://pelikone.fi/index.php/pelit
```

### What happens?

Ad placeholders:
![image](https://user-images.githubusercontent.com/84513173/147989613-69d3a092-3342-4d28-9fb4-36fe712e52f6.png)
![image](https://user-images.githubusercontent.com/84513173/147989855-332ae291-ffee-49df-9ef0-f5d359da6e47.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 95.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.40.2

</details>

### Other details:

```
pelikone.fi##.ad
pelikone.fi##.text-ad-container
```

**Comment by peace2000** [comment]
Done https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/b2267570220e086230128c7711bf60b64d27d00c
