### ISSUE TITLE
alypaa.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#395]
### List the website(s) you're having issues:

```
https://alypaa.com/keskustelu.php
```

### What happens?

Ad placeholder:
![image](https://user-images.githubusercontent.com/84513173/147990218-9b0154e7-0900-4581-bb48-fc24ce4095b2.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 95.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.40.2

</details>

### Other details:

```
alypaa.com#?#.section-inner:-abp-has(.banner-slot)
```

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/390e1f162d74bd1150cf3a5090306954d933288a
