### ISSUE TITLE
pelit.fi changed promotional news items

### ISSUE THREAD

**Issue by 07416** [finnish-easylist-addition/finnish-easylist-addition#398]
### List the website(s) you're having issues:
`https://www.pelit.fi/` ([archive.org](https://web.archive.org/web/20220115155711/https://www.pelit.fi/))

### What happens?

News posts with the `MAINOS` tag aren't hidden.

### Other details:
![image](https://user-images.githubusercontent.com/14923168/149627985-814589c2-134a-4933-8858-fa430a295c78.png)

**Comment by peace2000** [comment]
Thanks, fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/89fb847b8adb0538bbcaa7bac59111b2d5a3ff2e
