### ISSUE TITLE
suomikiekko.com, valioliiga.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#399]
### List the website(s) you're having issues:

```
https://www.suomikiekko.com/
```
```
https://www.valioliiga.com/
```

### What happens?

Empty button that does nothing in bottom menu on mobile. 

![Screenshot_20220122-212939__01](https://user-images.githubusercontent.com/84513173/150653479-f519f36e-31d5-4290-b57b-25d615d916f2.jpg)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 96.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.40.8

</details>

### Other details:

Happens because `valioliiga.com##[href$="/vedonlyonti/"]` and `suomikiekko.com##[href$="/pitkavetovihjeet/"]` filters.

Maybe change to:
```
suomikiekko.com#?#.menu-item:-abp-has([href$="/pitkavetovihjeet/"])
```
```
valioliiga.com#?#.menu-item:-abp-has([href$="/vedonlyonti/"])
```

Or have both if needed.

**Comment by peace2000** [comment]
Thanks, fixed: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/4f45528c8a4c520d780b85746a4d6aa3e15902d3
