### ISSUE TITLE
karjalainen.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#400]
### List the website(s) you're having issues:

```
https://www.karjalainen.fi/talous/britannian-laukkaava-inflaatio-iskee-kipeasti-pienituloisiin-ruokajakeluissa-odotetaan-avun-tarpeen-kasvavan-selvasti-tana-vuonna
```

### What happens?

![image](https://user-images.githubusercontent.com/84513173/150716689-5d427028-6856-445c-a0a0-489d36bb4d0b.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 96.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.40.8

</details>

### Other details:

```
karjalainen.fi#?#.card-container:-abp-contains(Mainos alkaa)
```

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/624cac9c728802644543263a8f881a9bf669f03e
