### ISSUE TITLE
nettiauto.com

### ISSUE THREAD

**Issue by theel0ja** [finnish-easylist-addition/finnish-easylist-addition#401]
### List the website(s) you're having issues:

* `https://www.nettiauto.com/yritys/1134418`

### What happens?

<img width="1043" src="https://user-images.githubusercontent.com/5832930/151682854-99b37936-e0a3-4e55-9cf1-07d65a889e48.png">

No cars are visible even through there should be 27 of them

### Other details:

From the same company as #397. Maybe should check all rules regarding that company's websites?

**Comment by Nojuuu** [comment]
Also ad here:
`https://www.nettivene.com/haku?q&search&ffs=Y&boat_type_list=A&regionNames&whole_finland=Y`

![image](https://user-images.githubusercontent.com/84513173/151714741-a91356cd-d7a1-4288-ad61-755598253350.png)

**Comment by Nojuuu** [comment]
`www.nettiauto.com,www.nettikaravaani.com,www.nettikone.com,www.nettimarkkina.com,www.nettimokki.com,www.nettimoto.com,www.nettivaraosa.com,www.nettivene.com,www.nettivuokraus.com##.listing:not([data-id]):not(.tricky_link_listing)`

**Comment by peace2000** [comment]
Added `:not(.tricky_link_listing)` back https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/dbb1da6139247ef81b079880b9e3ced3d75dce40
