### ISSUE TITLE
app.mtvuutiset.fi do videos work?

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#404]
https://app.mtvuutiset.fi/artikkeli/8362974

When trying to view videos I get this error:

![kuva](https://user-images.githubusercontent.com/17256841/155386676-c795ccc6-349a-4a8e-829f-642c6e011b04.png)

But on private browsing, no issues.

How does it work for you @Nojuuu

**Comment by Nojuuu** [comment]
Worked fine for me when testing now, but that has been happening to me sometimes even on normal `mtvuutiset.fi` site, not sure what triggers it.

**Comment by Nojuuu** [comment]
Does that but without using `$script` make any difference for you, it seems to some reason make that error trigger less often on Brave's built in blocker?
https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/ac4fc1ae082db72b2a241fec57131fbbce8edbe2/Finland_adb.txt#L1019

That error is also always triggered with Vivaldi's built in blocker but haven't tested any fixes for it because you need to host list somewhere to use your own filters.

**Comment by Nojuuu** [comment]
It seems that removing `$script` also fixes it in Vivaldi for me, so I guess the filter just needs to be as fast as possible to process and in this case it's just a bit faster because it doesn't need to check if it's a script or not?

**Comment by Nojuuu** [comment]
I tested several times today an still didn't get that error, so I changed it here too: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/ad3901a6ed8087987790a5670f2cfe0216d0679a

**Comment by peace2000** [comment]
> It seems that removing `$script` also fixes it in Vivaldi for me, so I guess the filter just needs to be as fast as possible to process and in this case it's just a bit faster because it doesn't need to check if it's a script or not?

I think it's faster when there is `$script` because then it only checks that request for script type but now it checks it for every type.

I was recently advised by gorhill that narrowed requests are always better performance-wise:
https://www.reddit.com/r/uBlockOrigin/comments/p6d6np/whats_wrong_in_my_regex/

But if it seems to work better without `$script` then the change is of course good. Thanks for testing!

I haven't seen that error today actually.

**Comment by Nojuuu** [comment]
When using both at the same time and checking logger in uBO, it always showed the one without `$script` as the chosen one.
