### ISSUE TITLE
ylilauta.org anti adblock

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#408]
It seems Ylilauta has some kind of anti adblock. When opening a thread, an error will be displayed:

![kuva](https://user-images.githubusercontent.com/17256841/161422361-cbedc82c-63e7-4570-9e33-75fbaef22cbc.png)

Quick Google translation for those who don't understand the message just in case:

```
Some of the required files failed to load!

Make sure your browser isn't blocking them (for example, to block ads) and that your internet connection is working properly.

The page will refresh automatically shortly so you can try again ... 
```

The funny thing is that the error doesn't appear if I block all the profile pictures via `||ylilauta.org/$image` so I think it's an anti adblock that's disguised as a technical error.

Sample page:
`https://ylilauta.org/masiinat/129168251`

**Comment by peace2000** [comment]
Should fix https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/cb30992635ac0ade1bfe5c6f8d243f6642d7e493

**Comment by peace2000** [comment]
Still needed: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/ce6bdde2259c75be5fe9603d0308eec56b875eb6

**Comment by roninyymi** [comment]
Thanks for trying to make this site usable! Now it uses alert for this that doesn't respect "Block notifications" setting:

![ylilauta_alert](https://user-images.githubusercontent.com/102995640/161619412-77ba0ccd-354b-45d8-84fa-35d6ea778a57.png)

This is logic in code:
```
console.error('Toast could not be displayed properly for some reason, it probably does not fit in the viewport. ' +
    'Falling back to alert(), browsers should know how to display it properly.');
let alertMessage = message;
if (title !== null) {
    alertMessage = title + ': ' + alertMessage;
}
alert(alertMessage);
```

![ylilauta_error](https://user-images.githubusercontent.com/102995640/161620232-c091576c-341d-400e-a392-b051ca1dd5e3.png)

**Comment by peace2000** [comment]
Hmm, I cannot reproduce that... Have you updated your lists?

**Comment by theel0ja** [comment]
Fixed by allowing fcdn.lauta.media and allowing XHR requests to s1.adform.net from main domain ylilauta.org.

The ads are loaded via script from s1.adform.net from fcdn.lauta.media.

However, if your DNS provider blocks "s1.adform.net", the site throws alert()s. If you have a DNS blocker on OS level, you could try mitigate this by setting DoH server in your browser (supported in at least Chromium and Firefox).

**Comment by roninyymi** [comment]
> Hmm, I cannot reproduce that... Have you updated your lists?

I managed to get list updated (i don't know why it weren't even when pressing update button). Now this happens:

![yellow_error](https://user-images.githubusercontent.com/102995640/161662040-ff396ac4-1d28-4ddc-ae8b-73d7c69f50bb.png)

![yellow_warning](https://user-images.githubusercontent.com/102995640/161662045-52837178-3e26-42c2-b23c-dfe4a89bd58a.png)

Also there was empty spaces left from removing ads what is fixed with `||fcdn.lauta.media`

**Comment by theel0ja** [comment]
Fixed the empty space with https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/3b42651dd6b787dcf639366592b474f4a14e17df

**Comment by theel0ja** [comment]
They are now using alert() on Ylilauta 2.71.

https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/007678b2c4edb29d7c1eaf6b68b02742c934c3b0

Interestingly doesn't work on Firefox (98.0.2, uBO 1.42.0) but works on Chromium (100.0.4896.62@Win, uBO 1.41.8).

**Comment by roninyymi** [comment]
I think it is better to not disable/remove even partly those `ylilauta.org##.warning.toast` and `ylilauta.org##.error.toast` because that alert is more annoying than that toast. And now we are in this situation again because it triggers that if statement:


> Thanks for trying to make this site usable! Now it uses alert for this that doesn't respect "Block notifications" setting:
> 
> ![ylilauta_alert](https://user-images.githubusercontent.com/102995640/161619412-77ba0ccd-354b-45d8-84fa-35d6ea778a57.png)
> 
> This is logic in code:
> 
> ```
> console.error('Toast could not be displayed properly for some reason, it probably does not fit in the viewport. ' +
>     'Falling back to alert(), browsers should know how to display it properly.');
> let alertMessage = message;
> if (title !== null) {
>     alertMessage = title + ': ' + alertMessage;
> }
> alert(alertMessage);
> ```
> 
> ![ylilauta_error](https://user-images.githubusercontent.com/102995640/161620232-c091576c-341d-400e-a392-b051ca1dd5e3.png)

Maybe something cosmetic works like this? I haven't tested this yet.
```
ylilauta.org##.warning.toast:has-text(Virhe ladattaessa mainoksia):style(opacity: 0 !important;)
ylilauta.org##.warning.toast:has-text(Error loading advertisements):style(opacity: 0 !important;)
```

**Comment by theel0ja** [comment]
>Interestingly doesn't work on Firefox (98.0.2, uBO 1.42.0) but works on Chromium (100.0.4896.62@Win, uBO 1.41.8).

https://github.com/uBlockOrigin/uBlock-issues/issues/2079

**Comment by roninyymi** [comment]
> Maybe something cosmetic works like this? I haven't tested this yet.
> ```
> ylilauta.org##.warning.toast:has-text(Virhe ladattaessa mainoksia):style(opacity: 0 !important;)
> ylilauta.org##.warning.toast:has-text(Error loading advertisements):style(opacity: 0 !important;)
> ```
Tested with fresh ubuntu live-cd and uBlock Origin and no, this doesn't work any better.

**Comment by roninyymi** [comment]
> > Interestingly doesn't work on Firefox (98.0.2, uBO 1.42.0) but works on Chromium (100.0.4896.62@Win, uBO 1.41.8).
> 
> [uBlockOrigin/uBlock-issues#2079](https://github.com/uBlockOrigin/uBlock-issues/issues/2079)

Maybe [Scriptlet Doctor](https://github.com/JustOff/scriptlet-doctor) helps? ([source](https://github.com/uBlockOrigin/uBlock-issues/issues/235#issuecomment-581126972))

**Comment by peace2000** [comment]
Seems to work https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/c603548a14c682c7f51ebd9195ef6f6498033e34 update your lists and test (might take 10 minutes for lists to update). Only for uBO.

**Comment by peace2000** [comment]
Previous stopped working, new try: https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/master/Finland_adb_uBO_extras.txt

**Comment by peace2000** [comment]
This should be faster way to prevent that yellow box from appearing: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/c733dca05f923c1dca4494f4cb8493c2a54545b7

Cosmetic "`has-text`" filter works but it's slower as that box still blinks once.

**Comment by Bec-de-Xorbin** [comment]
Can you remove all ylilauta.org related stuff? Unfortunately it's a mess right now and breaks the site. Or is there a way in uBlock Origin to disable only this list to a specific site? I don't want to disable ad blocking completely in ylilauta.org nor I want to disable this list.

**Comment by peace2000** [comment]
DId that, and added a filter that partly helps.

**Comment by Alex-302** [comment]
It seems changed again https://github.com/AdguardTeam/AdguardFilters/issues/115728
But I cannot check due to error.

**Comment by KMatias123** [comment]
Would it be possible to patch the javascript? https://static.ylilauta.org/js/5.8/Library/Toast.js has the method called #show, where you could check for the ad notification string.

**Comment by Bec-de-Xorbin** [comment]
FYI: https://github.com/uBlockOrigin/uAssets/issues/14204#issuecomment-1743067004

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/d72ee6221806dc976755c20024ae41378774d118
