### ISSUE TITLE
telsu.fi

### ISSUE THREAD

**Issue by DandelionSprout** [finnish-easylist-addition/finnish-easylist-addition#409]
### List the website(s) you're having issues:

`https://www.telsu.fi/huomenna`

### What happens?

It seems to me that the site is aiming for a "Cat and mouse" strategy, so there seems to be ads and placeholders there at the moment.

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/22780683/168969047-48d3ea8b-bb48-4424-a5d7-54de2bc573d3.png)

</details>

### Your settings

- OS/version: Windows 11 x64
- Browser/version: Chrome 101.0.4951.67 x64
- Adblock Extension/version: uBO 1.43.4 + IDCAC 3.3.9

### Other details:

I propose:
```
||telsu.fi/telsu_top
telsu.fi###page > [id*=_]
telsu.fi##.footer > [id*=_]
```

Screenshot:
<details>

![image](https://user-images.githubusercontent.com/22780683/168968763-4803125c-4bbf-4c46-9dd5-1caae692ac38.png)

</details>

**Comment by peace2000** [comment]
Let's see first how this will turn out: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/6982a8caa094765bcbedf3e138ed66f65491e422

**Comment by peace2000** [comment]
Forgot this one: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/8489fb936ecb3115c9ccf618ee5eee188d26da0f

**Comment by peace2000** [comment]
Added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/fdb2046306dada7d510035f22de5328d0ad230b7 as well.

**Comment by peace2000** [comment]
Fine now, will be opened again if needed.
