### ISSUE TITLE
aamulehti.fi

### ISSUE THREAD

**Issue by sorsasampo** [finnish-easylist-addition/finnish-easylist-addition#41]
### List the website(s) you're having issues:

For example: `https://www.aamulehti.fi/a/201321208`

### What happens?

Anti-adblock popup "Ymmärrämme, että mainokset häiritsevät sinua".

### List Subscriptions you're using:

uBlock Origin defaults + finnish-easylist-addition.

### Your settings

- OS/version: Linux
- Browser/version: Firefox
- Adblock Extension/version: uBlock Origin 1.17.2

### Other details:

Popup location in DOM:

    html body div#container.containerDiv div.sc-hCbubC.btOEzx div.sc-bIKvTM.eGTEcF div.sc-kDhYZr.fKjNmg

They seem to randomize the CSS classes, so blocking this probably requires some selector wizardy.

**Comment by peace2000** [comment]
##.btOEzx.sc-hCbubC - this one blocks the whole page if applied as a filter

##.eGTEcF.sc-bIKvTM - the navigation bar under the blue top bar

##.fKjNmg.sc-kDhYZr - this is the ad blocking complaint

I reloaded the page many times and still those values stayed the same. So I don't think those values change every time at least and they seeminglt stay the same for multiple users also. Not many days ago I added a filter for that complaint. Back then it was

##.huCagr.sc-fFTYTi

But I'll make a pull request to add a filter for that new element. Let's see if it will change soon...

**Comment by theel0ja** [comment]
More discussion here: https://github.com/finnish-easylist-addition/finnish-easylist-addition/pull/42

**Comment by theel0ja** [comment]
This monstrosity seems to block it completely:

```
www.aamulehti.fi###container > div > div > div:has(div:last-of-type:has(div:has-text(Ymmärrämme, että mainokset häiritsevät sinua)))
```

I think that `:has()` is uBO only though.

**Comment by peace2000** [comment]
> 
> 
> This monstrosity seems to block it completely:
> 
> ```
> www.aamulehti.fi###container > div > div > div:has(div:last-of-type:has(div:has-text(Ymmärrämme, että mainokset häiritsevät sinua)))
> ```
> 
> I think that `:has()` is uBO only though.

Does not work for me if I whitelist that complaint window:

aamulehti.fi#@#.fKjNmg.sc-kDhYZr

**Comment by peace2000** [comment]
Or wait, I was stupid now. :D It works.

But, it just for ubo.

This works also and it's work Ubo and ABP

aamulehti.fi#@#.ad-div

**Comment by peace2000** [comment]
I was messing up a bit in some of comments (removed). Yes it seems to be ok.

**Comment by okiehsch** [comment]
Just fyi, you can disable the adblock detection by adding 
`aamulehti.fi##+js(setTimeout-defuser.js, adblockDetected, 0`

**Comment by j4riv** [comment]
Adblock nag is back, it is also on many other Almamedia's sites.

**Comment by okiehsch** [comment]
`aamulehti.fi##+js(setTimeout-defuser.js, adblockDetected, 0)`
still works on my end using Chromium or Firefox.
An alternative fix is 
`@@||aamulehti.fi^$generichide`

**Comment by theel0ja** [comment]
Looks like it's there only when I have disabled uMatrix/allowed third-parties in uMatrix.
