### ISSUE TITLE
tiketti.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#413]
@peace2000 

I'm not sure what to do with the big banner at the top, it looks like it can only be fixed properly for uBO?

![image](https://user-images.githubusercontent.com/84513173/181917997-3ff50fb1-7e08-4ad4-a72f-8e1e085ac443.png)

**Comment by peace2000** [comment]
Yeah it seems so. That can't be helped. ABP people should hurry in implementing styling injection: https://gitlab.com/eyeo/adblockplus/abc/adblockpluscore/-/issues/210 but progress has been slow...

Maybe use these for uBO?:

`tiketti.fi###front_big_event`
`tiketti.fi###tik_fixed:style(position: unset !important)`
`tiketti.fi###tiketti:style(margin-top: 0 !important)`

**Comment by Nojuuu** [comment]
```
tiketti.fi###front_big_event
tiketti.fi###tik_fixed.with-ebanner:style(top: 0 !important)
```

Maybe? Should I just leave the ad there for others or add `###front_big_event > span` or something for them?

**Comment by peace2000** [comment]
`tiketti.fi###front_big_event`
`tiketti.fi###tik_fixed.with-ebanner:style(top: 0 !important)`

Seems to be fine as well, actually, it alters the site less than my rules.

I don't see `span` elements under `###front_big_event` ?

**Comment by Nojuuu** [comment]
![image](https://user-images.githubusercontent.com/84513173/181924556-a9577a50-2e13-4c3b-af06-a63d8bbbc634.png)

**Comment by peace2000** [comment]
Oh.. didn't see `span` because I had other filters active...

Well, for ABP it's indeed either

`tiketti.fi###front_big_event > span`

Or nothing. Both results look annoying. But maybe better to add `tiketti.fi###front_big_event > span` anyway.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/92577ecca5b3b0ece99d88a7e6a7d13ce49d9070
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/e86fcaaa1d20c8a32cba4922c4b6ee78a8b71884

**Comment by Nojuuu** [comment]
I was  just thinking about `||tiketti.fi/tiedostot/b2022/Tiketti*_Paraati_$image,domain=tiketti.fi` too, so at least they would benefit from 2 images not loading?

**Comment by peace2000** [comment]
True, that would be good as well.

Maybe even

`||tiketti.fi/tiedostot/*/Tiketti*_Paraati_$image,domain=tiketti.fi` I think that removing the year would be even better?

**Comment by Nojuuu** [comment]
Yeah, that's fine too.

**Comment by Nojuuu** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/83429b3d295a568d047c04b8452dcb00845c6fa0
