### ISSUE TITLE
discoveryplus.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#424]
### List the website(s) you're having issues:

`https://www.discoveryplus.com/fi/video/atlantin-yli/traileri-kausi-3`

### What happens?

Ads

<details>
<summary>View image</summary>

![image](https://user-images.githubusercontent.com/84513173/188683887-9e4c60c8-4c01-45c4-83c6-e3a59438e0ec.png)

</details>

### List Subscriptions you're using:

Adblock List for Finland

### Other details:

--

**Comment by peace2000** [comment]
Hmm... https://github.com/uBlockOrigin/uAssets/issues/14365

It might not be fixable.

**Comment by peace2000** [comment]
![kuva](https://user-images.githubusercontent.com/17256841/188687557-db644726-f1f7-4934-b28c-2017c80bf5ff.png)

**Comment by Nojuuu** [comment]
> It might not be fixable.

Looks like it... I can't figure anything out. You can close this if you don't either.

**Comment by Nojuuu** [comment]
Doesn't seem to show ad if you manage to click that 10s rewind button fast enough :D Idk if that helps with anything.

**Comment by peace2000** [comment]
Actually there's no need to rush. If you first click rewind and then play, the video starts to play without that ad.

![kuva](https://user-images.githubusercontent.com/17256841/188710563-af447c38-7e4d-4b11-a02e-b5eff32bbe5f.png)

**Comment by peace2000** [comment]
This kind of functionality could help https://github.com/uBlockOrigin/uBlock-issues/issues/2229 maybe...

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16998#issuecomment-1453607989 https://github.com/uBlockOrigin/uAssets/commit/0e81aa16aa30c489b4a6ed05f3a8f2d8128ae515

Maybe these ads not based on Hulu SSAI yet.

Also these may need changes in AdGuard Tracking Protection (aka AdGuard Spyware) and EasyPrivacy: https://github.com/AdguardTeam/AdguardFilters/issues/144948#issuecomment-1459844974

**Comment by peace2000** [comment]
uBO's internal filters seem to handle this currently:

`discoveryplus.*##+js(json-prune, data.attributes.config.freewheel data.attributes.config.featureFlags.dPlayer)`

No ads for me at least.

**Comment by Nojuuu** [comment]
I still see ads, at least in those trailers.

**Comment by peace2000** [comment]
Got these from stephenhawk8054

`discoveryplus.com##+js(json-prune, data.attributes.ssaiInfo.forecastTimeline data.attributes.ssaiInfo.vendorAttributes.nonLinearAds data.attributes.ssaiInfo.vendorAttributes.videoView)`
`discoveryplus.com##+js(xml-prune, Period:not([duration*="M"]), , .mpd)`

Can you test them @Nojuuu ? At least seem to work for me.

**Comment by Nojuuu** [comment]
Works for me too

**Comment by peace2000** [comment]
https://github.com/uBlockOrigin/uAssets/commit/9cfdf6fb606fd42dbe7ac44118a112393bb2264b

**Comment by peace2000** [comment]
Not a Finnish site anyway so maybe this should be closed.

**Comment by krystian3w** [comment]
Also commit is outdated, I see someone removed now `!#if ext_devbuild` to force run scriplet in 1.50.0+?
