### ISSUE TITLE
sijoittaja.fi

### ISSUE THREAD

**Issue by anttironty** [finnish-easylist-addition/finnish-easylist-addition#425]
### List the website(s) you're having issues:

`https://www.sijoittaja.fi/`

### What happens?

Whole `.frontpage#content` `div` disappears, that is the container containing links to all articles.

### List Subscriptions you're using:

Adblock List for Finland

### Other details:

Filter that causes this: `sijoittaja.fi#?#.frontpage#content:-abp-has(.hs-cta-wrapper)`

**Comment by peace2000** [comment]
Thanks for the report, they probably have changed the site. Removed that rule: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/02eae1d5151c7010b1bfa5c62a29bf2c8147a638

**Comment by peace2000** [comment]
I'll check later if new rules are needed for tha page.
