### ISSUE TITLE
blank feed on facebook . com 

### ISSUE THREAD

**Issue by manuel-martinez-dev** [finnish-easylist-addition/finnish-easylist-addition#429]
### List the website(s) you're having issues:

Facebook . com

### What happens?

Facebook's main feed breaks, goes blank, due to the following filter:

`facebook.com#?#div[role="feed"] > div:-abp-has(a[class][href][role][tabindex]:has-text(Sponsoroitu))`

### List Subscriptions you're using:

Adblock Plus extension

Easyprivacy
ABP filters
Dandelion Sprout's Nordic Filters+EasyList

### Your settings

- OS/version: Ubuntu 22.04.1 LTS
- Browser/version: Google Chrome, Version 106.0.5249.119 (Official Build) (64-bit)
- Adblock Extension/version: ABP Version number 3.14.2

### Other details:

Please see below for an example of the problem.

#### Screenshot:
![FB-broken-Fin-b](https://user-images.githubusercontent.com/40897997/197562435-f2d7ab05-680b-4c7a-ac44-ed2cb29196f3.jpg)
![FB-broken-Fin](https://user-images.githubusercontent.com/40897997/197562442-60705f5a-b53d-49ee-bfb8-3e3d464a3dd9.jpg)

**Comment by peace2000** [comment]
I fixed this few days ago. FB changed their site, making previously perfectly fine rule bad.

**Comment by peace2000** [comment]
I'll close this as this was fixed some days ago.
