### ISSUE TITLE
rumba.fi

### ISSUE THREAD

**Issue by 07416** [finnish-easylist-addition/finnish-easylist-addition#430]
### List the website(s) you're having issues:

`https://www.rumba.fi/page/2/` 
([archive.org](https://web.archive.org/web/20221205081113/https://www.rumba.fi/page/2/))

### What happens?

A promotional post `Ilmoitus:` is displayed in the feed.

### Other details:

suggested filter (not ready, I don't know how to anchor `^` the [procedural filter](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters)):

    ##div.listing-container.bg-white.p-3.mb-6:has-text(/Ilmoitus:/)

![image](https://user-images.githubusercontent.com/14923168/205587062-1de559a8-39d5-4c62-ac1f-5e9dd41c659f.png)

**Comment by peace2000** [comment]
I'm not sure why putting `^` doesn't work in this case, but I'll take a different approach:

`rumba.fi#?#.listing-container:-abp-has(> [href^="https://www.rumba.fi/advertoriaali/"])`

`:has()` filters will soon be non-procedural so I'll rather use them.

https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/72c3d1602adbc66d3d2a8ba2438722d43687dd02

**Comment by peace2000** [comment]
Wait a sec, a sister domain has already working rule....

**Comment by peace2000** [comment]
This way, rather: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/433894a9edda13884e6ead7306b5e846144732d2
