### ISSUE TITLE
hs.fi videos not playing

### ISSUE THREAD

**Issue by teepeevee** [finnish-easylist-addition/finnish-easylist-addition#432]
### List the website(s) you're having issues:
https://www.hs.fi/
Example page with video not playing when uBlock Origin & Adblock List for Finland on:
https://www.hs.fi/ulkomaat/art-2000009343010.html

### What happens?
Videos are not playing and stay just in loading state

### List Subscriptions you're using:
uBlock Origin & Adblock List for Finland

### Your settings

- OS/version: macOS 13.2.1
- Browser/version: MS Edge 110.0.1587.41 
- Adblock Extension/version: uBlock Origin

**Comment by peace2000** [comment]
It seems that link was a live event that ended, here's another video https://www.hs.fi/politiikka/art-2000009392084.html

**Comment by peace2000** [comment]
,

**Comment by teepeevee** [comment]
I just tested disabling other filters one by one and looks like AdGuard Annoyances causes hs.fi videos not to play so I'll report this there and this can be closed.
