### ISSUE TITLE
muropaketti.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#433]
### List the website(s) you're having issues:

`https://muropaketti.com/`

### What happens?

<img src="https://user-images.githubusercontent.com/84513173/219955476-b53d0559-aa1c-4cad-8d39-0c9ba6012102.png" width="500" height="600">

Images sometimes not loading? Does not seem to happen if I disable uBO.

**Comment by peace2000** [comment]
Hmm. Can't repro. When you test, you should make the new page loads always in new incognito mode.

**Comment by Nojuuu** [comment]
Can you repro with other browsers/blockers? Allowing `googletagmanager.com` seems to fix this for me.

**Comment by peace2000** [comment]
I tried but I couldn't repro. You still have this? Does this happen in incognito mode?

**Comment by Nojuuu** [comment]
![image](https://user-images.githubusercontent.com/84513173/221969775-4ec71406-339b-4bb9-81fd-8ca7720a53c5.png)


![image](https://user-images.githubusercontent.com/84513173/221969920-5a6eb29e-6857-40b2-8763-18a167a06fa1.png)

**Comment by Nojuuu** [comment]
And sometimes / some days / some articles works fine

![image](https://user-images.githubusercontent.com/84513173/222183994-fd417bf9-c38d-444a-93d9-0e2197e2cfa1.png)

**Comment by Nojuuu** [comment]
Hmm, could you test with urls that have e.g. 

```
/elokuvat/elokuvauutiset/
/pelit/peliuutiset/
```

in path?

**Comment by peace2000** [comment]
Sorry for delay.

I managed to repro with this link: https://muropaketti.com/pelit/peliuutiset/the-last-of-us-tahti-pedro-pascal-esiintyy-suomalaispelia-esittelevassa-lyhytelokuvassa/

Hmm...

**Comment by peace2000** [comment]
A whitelist rule seems to the only solution, didn't get this to with redirect-filters.

How about you? @Nojuuu

**Comment by Nojuuu** [comment]
Found this:


```html

<script>

if (/\/viihde\/|\/peliuutiset\/|\/elokuvauutiset\//.test(window.location.href)) {
    console.log('add "noImages" class to body')
    document.body.classList.add("noImages");
}

</script>
```


```adblock
muropaketti.com##body:remove-class(noImages)
```

So probably can keep blocking for uBO atleast?

**Comment by peace2000** [comment]
That's a good discovery. Probably better to go with :style as user styles have a precedence over +js.

Easyprivacy doesn't accept uBO specific syntax at least yet, so I'll make PR to uBO's internal filters, also add a fix to the Finnish list.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/0176f574e4f7b8820d9bf053ddeab00968fb8508

https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/ca0d15f554fe56d0876965511ed8e2b367f29d8a

https://github.com/uBlockOrigin/uAssets/commit/bba81477f0f3958734c673f02162c393ea6a220e
