### ISSUE TITLE
netti-tv.fi

### ISSUE THREAD

**Issue by DandelionSprout** [finnish-easylist-addition/finnish-easylist-addition#435]
### List the website(s) you're having issues:

`https://netti-tv.fi/ohjelma/inui`

### What happens?

Large placeholder above the main feed.

### Your settings

- OS/version: Windows 11 22H2 x64
- Browser/version: Chrome 110.0.5481.178 x64
- Adblock Extension/version: uBO 1.47.4 + I Don't Care About Cookies 3.4.6

### Other details:

I propose `netti-tv.fi###main > div[style^="min-height:"]`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/223593848-f0e8122c-bc40-4505-833b-e0b9f1268271.png)

</details>

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/c8e2d567cf128240794c7d7aa01590d3052bc167
