### ISSUE TITLE
Finnish list is causing Anti-AdBlock message

### ISSUE THREAD

**Issue by Sonic5435325** [finnish-easylist-addition/finnish-easylist-addition#437]
### List the website(s) you're having issues:

https://www.awempire.com

### What happens?
Caused by `##div[id*="AdContainer"]`
![Screenshot from 2023-04-12 17-14-26](https://user-images.githubusercontent.com/89158249/231586901-07491526-98f0-4200-a7ad-ce09fe5f8523.png)

### List Subscriptions you're using:
EasyList
EasyList Finnish

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by peace2000** [comment]
Even if I disable cosmetic filtering (and that rule), the site is still blocked by Easylist and Peter Lowe's list as an ad server:

![kuva](https://user-images.githubusercontent.com/17256841/231833170-353e89b7-2701-4912-83e5-c34c70cfd5a6.png)

**Comment by peace2000** [comment]
No more details provided, so closing this for now.
