### ISSUE TITLE
terveyskirjasto.fi (Duodecim) - cookie modal

### ISSUE THREAD

**Issue by 07416** [finnish-easylist-addition/finnish-easylist-addition#446]
### List the website(s) you're having issues:

`https://www.terveyskirjasto.fi/`

### What happens?

A cookie overlay appears.

### List Subscriptions you're using:

Stock uBlock Origin with this list.

### Your settings

- Browser/version: Mozilla Firefox 115.0.2
- Adblock Extension/version: uBlock Origin 1.50.0

### Other details:

![image](https://github.com/finnish-easylist-addition/finnish-easylist-addition/assets/14923168/28e83985-6113-4085-abc9-47b933c28005)

**Comment by androidkotlindev** [comment]
uBO doesn't block cookie notices/modals by default. Enabling "EasyList – Cookie Notices" should hide the modal.

**Comment by 07416** [comment]
I recalled that cookie banners are within the scope of the list. 

The Easylist cookie list caused some breakage, last I tried. I use the 'AdGuard – Cookie Notices' list.

**Comment by peace2000** [comment]
Hi, cookie banners are not within the scope of the Finnish list itself.

They can be handled by the Easylist cookie list or Adguard cookie list.

Easylist cookie list issues can be reported here: https://github.com/easylist/easylist/issues

Adguard here: https://github.com/AdguardTeam/AdguardFilters/issues

You can use both lists or the other one.

Easylist Cookie list might cover Finnish sites better as me and @Nojuuu have contributed quite a lot various filters for that list.

In uBO, remember to also select uBO's own cookie dialog filters:

![kuva](https://github.com/finnish-easylist-addition/finnish-easylist-addition/assets/17256841/5201093a-e57c-4a62-8369-e71735e3c7c3)

It covers sites that require filter syntax that is not allowed outside of uBO's own lists, for security reasons.

This repo also has a separate discussion for GDPR banners https://github.com/finnish-easylist-addition/finnish-easylist-addition/discussions/416 I don't mind if you report GDPR stuff there. (But they are still not handled directly in the Finnish list as it's for ads only).
