### ISSUE TITLE
Implement better update method for the Version number and Last modified date

### ISSUE THREAD

**Issue by theel0ja** [finnish-easylist-addition/finnish-easylist-addition#45]
I mean these:

https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/ae873cfb88a566d791af78d6a44c4b3e944c171d/Finland_adb.txt#L2-L5

**Comment by theel0ja** [comment]
Probably something similar to old Wiltteri (https://github.com/wiltteri/source) would be great.

I mean have multiple files named like `general-block.txt`, `general-hide.txt`, `specific-block.txt` and so on. And then combine them together to a single file.

**Comment by peace2000** [comment]
Personally I find having multiple files more complicated and prefer having just a single file that is divided into sections as it's now. :)

**Comment by theel0ja** [comment]
Well, just going to edit when merging a PR.
