### ISSUE TITLE
verkkouutiset.fi rule blocking the articles

### ISSUE THREAD

**Issue by mrkukov** [finnish-easylist-addition/finnish-easylist-addition#451]
Line:
https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/14b345b5534d87b312f105c3afc0caa5c7b9e57c/Finland_adb.txt#L1145

Causing article content/text to not show up at:
https://www.verkkouutiset.fi/

**Comment by Nojuuu** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/8fa6e4202fdf27335eecc215283be6cf6e0edb2e should fix it
