### ISSUE TITLE
Facbook tärisee

### ISSUE THREAD

**Issue by survivor303** [finnish-easylist-addition/finnish-easylist-addition#452]
Facebookin postaukset tärisee.

Löysin rivin, joka ongelman tuottaa:
facebook.com#?#[role="feed"] [data-pagelet^="FeedUnit_"]:has([aria-label="Sponsoroitu"])

**Comment by peace2000** [comment]
Jopas jotain. Kummallinen ongelma. Tuo sääntö on pelittänyt pitkään ongelmitta. Facebook muuttanut jotain selvästi. Poistin säännön käytöstä ja tutkin aihetta lisää kun ehdin.

https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/0fa211e053cd90c0f5af4091d4d684993824afcf
