### ISSUE TITLE
Maybe move annoyances to Finnish Annoyance list

### ISSUE THREAD

**Issue by theel0ja** [finnish-easylist-addition/finnish-easylist-addition#47]
Such as "Supersää" on is.fi:

![image](https://user-images.githubusercontent.com/5832930/49239122-9a471480-f40a-11e8-839f-6b3ac7373f66.png)

https://github.com/finnish-easylist-addition/finnish-annoyance-list

**Comment by peace2000** [comment]
I would remove or move them to annoyance list. It's ok idea. They are not ads anyway.
