### ISSUE TITLE
xxl.fi cookie notice

### ISSUE THREAD

**Issue by jounihh** [finnish-easylist-addition/finnish-easylist-addition#57]
### List the website(s) you're having issues:

xxl.fi

### What happens?

This
![image](https://user-images.githubusercontent.com/40239267/49965427-d22f7b00-ff25-11e8-83f5-e7427d9808b2.png)

### List Subscriptions you're using:

Adguard's Annoyance List causes the problem

### Your settings

- OS/version:  windows 10
- Browser/version: waterfox
- Adblock Extension/version: nano adblock

**Comment by theel0ja** [comment]
Hmm I'd report to upstream.

**Comment by jounihh** [comment]
on nano you could do:
xxl.fi##+js(nanop-easy-set-cookie.js,cookies-accepted=true)

**Comment by krystian3w** [comment]
```
nanoMakeThirdPartyFiltersPrivileged false
      nanoMakeUserFiltersPrivileged false
```

this is should checked to true?

**Comment by jounihh** [comment]
> 
> 
> ```
> nanoMakeThirdPartyFiltersPrivileged false
>       nanoMakeUserFiltersPrivileged false
> ```
> 
> this is should checked to true?

yes

**Comment by krystian3w** [comment]
And we can not avoid creating it every refresh (not embedded in the scriptlet and AdGuard do not add if to detect cookie exist)?

**Comment by jounihh** [comment]
> 
> 
> And we can not avoid creating it every refresh (not embedded in the scriptlet and AdGuard do not add if to detect cookie exist)?

i don't think so

**Comment by krystian3w** [comment]
Glitch in IDCAC list:

`xxl.fi#@#.cookiewarning:not(body):not(html):not(.main)`

**Comment by peace2000** [comment]
This can be closed ad they don't have that upper bar anymore. They have a new cookie notification on the right side of the page that is easy to block.

**Comment by krystian3w** [comment]
`xxl.fi##.js-newsletter.newsletter-large` cut in Fanboy Annoyance?

**Comment by peace2000** [comment]
@krystian3w It seems so but isn't the point of annoyance list to block newsletters that are usually considered annoying?
