### ISSUE TITLE
Too aggressive rule!

### ISSUE THREAD

**Issue by THEtomaso** [finnish-easylist-addition/finnish-easylist-addition#6]
### Issue:
All images which contains the word "**casino**" are blocked!

### Examples:
```
http://www.hotflick.net/u/g/?d=5345408
https://www.google.com/search?tbm=isch&q=casino
```

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
Adblock List for Finland

### Problem rule:
`##a[href*="casino"]>img`

### Fix:
The above rule should be removed!

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.2.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by DandelionSprout** [comment]
I've accomodated for this in #5, on the presumption that this repo's owner (who is not me) were to accept that pull request.

**Comment by theel0ja** [comment]
I assume it was added by the original author to block casino ads, but it'd add too many false positives, so going to remove it.

**Comment by theel0ja** [comment]
#5 seems to fix this.

**Comment by THEtomaso** [comment]
> I assume it was added by the original author to block casino ads

Yeah, I reported this rule to him a while ago.
He refused to remove it.
