### ISSUE TITLE
telsu.fi broken

### ISSUE THREAD

**Issue by puskala** [finnish-easylist-addition/finnish-easylist-addition#70]
### List the website(s) you're having issues:

<code>https://www.telsu.fi/</code>

### What happens?

Telsu.fi fails to load channel logo images, the bar indicating current time and background colors for current/next programs. This happens in HORIZONTAL (not vertical, the default) view.

### List Subscriptions you're using:

FIN: Adblock List for Finland​

### Your settings

- OS/version: OS X El Capitan 10.11.6
- Browser/version: Safari 11.1.2
- Adblock Extension/version: uBlock Origin v1.16.0

### Other details:

The filter

`telsu.fi$third-party`

is the one causing problems. Copying the whole filter list into personal filters and removing this one fixes the problem.

**Comment by theel0ja** [comment]
Can't reproduce on Firefox (ubuntu, ubo 1.17.4) or Chromium (ubuntu, nano 1.0.0.83). Could you have a screenshot?

**Comment by puskala** [comment]
Now this is most peculiar. I can't reproduce the issue any longer myself. I'm starting to suspect something unrelated to adblocking.

I will now hold my horses until I can reliably reprodue it. Sorry for the time wasted.
