### ISSUE TITLE
Blocked pages in PDF Viewer again (Adblock List for Finland)

### ISSUE THREAD

**Issue by THEtomaso** [finnish-easylist-addition/finnish-easylist-addition#76]
### Issue:
Pages gets blocked, when using online PDF Viewers.

### Example:
`http://ipaper.ipapercms.dk/Nobia/HTH/NO/HTHDetmoderneliv/`

### How to reproduce:
Flip through the pages..
Everything from page 4 to 108 is blocked!

### Problem filter:
* Adblock List for Finland

### Problem rule:
`##DIV[class*="ad-element"]`

### Reference:
This is the same issue which I reported here:
https://github.com/finnish-easylist-addition/finnish-easylist-addition/issues/38/
I can only assume that many other sites are affected as well.

### Possible fix:
The blocking rule could be changed to this:
`##DIV[class*="ad-element"]:not("spread-elements")`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.2.2 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.6 (XUL)

**Comment by theel0ja** [comment]
I recommend you to make pull requests :)

**Comment by THEtomaso** [comment]
@theel0ja:
Looking at my suggested rule now, I think perhaps the syntax isn't correct.
Should probably be like this:
`##DIV[class*="ad-element"]:not(.spread-elements)`

**Comment by THEtomaso** [comment]
@theel0ja:
This should also make the following exception rule redundant:
`apotek1.no#@#DIV[class*="ad-element"]`

**Comment by krystian3w** [comment]
You see in html:

```html
<"spread-elements">

bla bla bla

</"spread-elements">
```

**Comment by THEtomaso** [comment]
This issue has been fixed, krystian3w.
Take a look at the commit above.
It works.
