### ISSUE TITLE
dplay.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#8]
Watching videos on this site with adblocker won't work as you will get a complaint to disable adblocker. Also after fixing the complaint with a proper filter, ads are shown again.

A sample url:

`https://www.dplay.fi/ohjelmat/fixer-upper`

Filters that fix the issue:

To make videos to work despite adblocker:
`@@||fwmrm.net/ad/$script,domain=dplay.fi`

To block ads that are displayed during playback of videos (a.k.a commercial breaks):
`||dniadops-a.akamaihd.net/video-assets/$media,domain=www.dplay.fi`

**Comment by theel0ja** [comment]
Should've been fixed by #5.
