### ISSUE TITLE
www.mikrobitti.fi - antiadblock notification

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#82]
`https://www.mikrobitti.fi/` has anti-adblock notification. How to block it?

**Comment by jounihh** [comment]
mikrobitti.fi##+js(setInterval-defuser.js,checkBait)

**Comment by jounihh** [comment]
mikrobitti.fi##+js(setTimeout-defuser.js,,loadAd)

**Comment by peace2000** [comment]
Seems to be doing the trick. Thank you. I'll make a pull request.
