### ISSUE TITLE
Santander Bank (earlier BZWBK) - private messages are blocked.

### ISSUE THREAD

**Issue by seba2282** [finnish-easylist-addition/finnish-easylist-addition#89]
Hello, when I have activate Juvander's list, messages on Polish Santander Bank are blocked. Only help deactivate list filter.
Can help?

**Comment by peace2000** [comment]
Url of the site?

**Comment by seba2282** [comment]
https://www.centrum24.pl/centrum24-web/login 
And problem is when you are logged. Client doesn't see any messages.

**Comment by jounihh** [comment]
can you take a screenshot from the logger window like this:
![image](https://user-images.githubusercontent.com/40239267/53000314-bddd9200-3430-11e9-815f-a65fa3f483cb.png)

**Comment by jounihh** [comment]
i have never used adguard but this rule should fix the issue:
centrum24.pl#@#DIV[class*="ad-item-wrapper"]

**Comment by seba2282** [comment]
That the same have on ublock origin or nano adblocker. In all messages are blocked by Juvander's.
I will test your rule and will be work, you can add that to filter?

**Comment by seba2282** [comment]
Works. Please add that and thanks for helping.

**Comment by jounihh** [comment]
i can't because i don't have write access

**Comment by seba2282** [comment]
Ok. Thanks for help. 
Best Regards

**Comment by theel0ja** [comment]
@jounihh Send a PR

**Comment by jounihh** [comment]
@theel0ja #90

**Comment by seba2282** [comment]
Rule, what you added earlier @jounihh, helped me. Now I test without rules and after updated filters, I don't see messages in Santander bank. Can you someone fix that?

**Comment by jounihh** [comment]
> 
> 
> Rule, what you added earlier @jounihh, helped me. Now I test without rules and after updated filters, I don't see messages in Santander bank. Can you someone fix that?
> 
> After add rule centrum24.pl#@#DIV[class*="ad-item-wrapper"] start work.

it hasn't been deleted yet

**Comment by seba2282** [comment]
@jounihh, but will be fix soon?

**Comment by jounihh** [comment]
> 
> 
> @jounihh, but will be fix soon?

hmmm... 
time will tell... the fix may come in a minute... or in a week...
but nobody knows...
except @theel0ja 
yes

**Comment by seba2282** [comment]
So I will waiting.

**Comment by theel0ja** [comment]
Send PR, if #90 doesn't fix it. Merging #90 now.

**Comment by seba2282** [comment]
2 hours ago, when I logged to bank site and after I tried open messages, all was hidded and rule what gave @jounihh, still was needing. I try after moment log in again, when I will be on PC. Thanks for trying help me 🙂

**Comment by seba2282** [comment]
Still Is blocked. Only rule @jounihh help me.

**Comment by krystian3w** [comment]
Filter no exsist in Finland list?

AdGuard update own filters in 1-3 hours interval.

<sup>(AdGuard odświeża listy na swoim serwerze co mniej-więcej okres 1-3 godzin jak ktoś dokona poprawek)</sup>.

**Comment by seba2282** [comment]
I logged on Santander and had still blocked messages and used rule from that topic. Maybe something changed now, but tomorrow will try log in again and test all works or not.

**Comment by krystian3w** [comment]
Also try send AdGuard logger with checked form field "blocked".

> ![obraz](https://user-images.githubusercontent.com/35370833/53208096-e4b8e580-3635-11e9-97d5-a8c1d1766ae2.png) |
> --- |

**Comment by seba2282** [comment]
Thanks all. Now works with chrome + adguard extension and Firefox + Adguard extension. Messages are working normally and see them.

**Comment by theel0ja** [comment]
Closed as per @seba2282's request via email.
