### ISSUE TITLE
foxplay.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#9]
If you are watching videos on foxplay.fi you will get a complaint to disable adblocker and videos cannot be properly watched.

A sample url:
`https://www.foxplay.fi/sarjat/the-walking-dead/jaksot/jakso-6`

A filter that fixes it:
`@@||www.foxplay.fi/compiled/js/ads.js$script`

**Comment by theel0ja** [comment]
Fixed in #5.
