### ISSUE TITLE
wrong filter for kaleva.fi

### ISSUE THREAD

**Issue by mapx-** [finnish-easylist-addition/finnish-easylist-addition#98]
see
https://www.reddit.com/r/uBlockOrigin/comments/b3a03i/pictures_blocked/

`||kaleva.fi*/smart_ads` => is breaking the page

**Comment by jounihh** [comment]
my bad sorry

**Comment by q2946027** [comment]
On mobile pictures and weather widget are still blocked on the front page. All is fine inside articles.

**Comment by theel0ja** [comment]
Any PR to fix?

**Comment by mapx-** [comment]
just remove that filter `||kaleva.fi*/smart_ads`
